// Code generated by ent, DO NOT EDIT.

package usersettings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usersettings type in the database.
	Label = "user_settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldTwoFactor holds the string denoting the two_factor field in the database.
	FieldTwoFactor = "two_factor"
	// FieldNightMode holds the string denoting the night_mode field in the database.
	FieldNightMode = "night_mode"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeSecondFactorTarget holds the string denoting the second_factor_target edge name in mutations.
	EdgeSecondFactorTarget = "second_factor_target"
	// EdgeNotificationTargetDevices holds the string denoting the notification_target_devices edge name in mutations.
	EdgeNotificationTargetDevices = "notification_target_devices"
	// Table holds the table name of the usersettings in the database.
	Table = "user_settings"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "user_settings"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_user_settings"
	// SecondFactorTargetTable is the table that holds the second_factor_target relation/edge.
	SecondFactorTargetTable = "user_devices"
	// SecondFactorTargetInverseTable is the table name for the UserDevice entity.
	// It exists in this package in order to avoid circular dependency with the "userdevice" package.
	SecondFactorTargetInverseTable = "user_devices"
	// SecondFactorTargetColumn is the table column denoting the second_factor_target relation/edge.
	SecondFactorTargetColumn = "user_settings_second_factor_target"
	// NotificationTargetDevicesTable is the table that holds the notification_target_devices relation/edge.
	NotificationTargetDevicesTable = "user_devices"
	// NotificationTargetDevicesInverseTable is the table name for the UserDevice entity.
	// It exists in this package in order to avoid circular dependency with the "userdevice" package.
	NotificationTargetDevicesInverseTable = "user_devices"
	// NotificationTargetDevicesColumn is the table column denoting the notification_target_devices relation/edge.
	NotificationTargetDevicesColumn = "user_settings_notification_target_devices"
)

// Columns holds all SQL columns for usersettings fields.
var Columns = []string{
	FieldID,
	FieldUUID,
	FieldTwoFactor,
	FieldNightMode,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "user_settings"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_user_settings",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTwoFactor holds the default value on creation for the "two_factor" field.
	DefaultTwoFactor bool
	// DefaultNightMode holds the default value on creation for the "night_mode" field.
	DefaultNightMode bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserSettings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUUID orders the results by the UUID field.
func ByUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUUID, opts...).ToFunc()
}

// ByTwoFactor orders the results by the two_factor field.
func ByTwoFactor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTwoFactor, opts...).ToFunc()
}

// ByNightMode orders the results by the night_mode field.
func ByNightMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNightMode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// BySecondFactorTargetField orders the results by second_factor_target field.
func BySecondFactorTargetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSecondFactorTargetStep(), sql.OrderByField(field, opts...))
	}
}

// ByNotificationTargetDevicesCount orders the results by notification_target_devices count.
func ByNotificationTargetDevicesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNotificationTargetDevicesStep(), opts...)
	}
}

// ByNotificationTargetDevices orders the results by notification_target_devices terms.
func ByNotificationTargetDevices(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationTargetDevicesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
	)
}
func newSecondFactorTargetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SecondFactorTargetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, SecondFactorTargetTable, SecondFactorTargetColumn),
	)
}
func newNotificationTargetDevicesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationTargetDevicesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NotificationTargetDevicesTable, NotificationTargetDevicesColumn),
	)
}
