// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMail holds the string denoting the mail field in the database.
	FieldMail = "mail"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// FieldBlacklisted holds the string denoting the blacklisted field in the database.
	FieldBlacklisted = "blacklisted"
	// FieldRemoved holds the string denoting the removed field in the database.
	FieldRemoved = "removed"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUserDetails holds the string denoting the user_details edge name in mutations.
	EdgeUserDetails = "user_details"
	// EdgeUserSettings holds the string denoting the user_settings edge name in mutations.
	EdgeUserSettings = "user_settings"
	// EdgeActivationCode holds the string denoting the activation_code edge name in mutations.
	EdgeActivationCode = "activation_code"
	// EdgeVerificationCode holds the string denoting the verification_code edge name in mutations.
	EdgeVerificationCode = "verification_code"
	// EdgeSecondFactorCode holds the string denoting the second_factor_code edge name in mutations.
	EdgeSecondFactorCode = "second_factor_code"
	// EdgeResetCode holds the string denoting the reset_code edge name in mutations.
	EdgeResetCode = "reset_code"
	// EdgeUserDevices holds the string denoting the user_devices edge name in mutations.
	EdgeUserDevices = "user_devices"
	// EdgeUserActions holds the string denoting the user_actions edge name in mutations.
	EdgeUserActions = "user_actions"
	// EdgeUserRoles holds the string denoting the user_roles edge name in mutations.
	EdgeUserRoles = "user_roles"
	// Table holds the table name of the user in the database.
	Table = "users"
	// UserDetailsTable is the table that holds the user_details relation/edge.
	UserDetailsTable = "user_details"
	// UserDetailsInverseTable is the table name for the UserDetails entity.
	// It exists in this package in order to avoid circular dependency with the "userdetails" package.
	UserDetailsInverseTable = "user_details"
	// UserDetailsColumn is the table column denoting the user_details relation/edge.
	UserDetailsColumn = "user_user_details"
	// UserSettingsTable is the table that holds the user_settings relation/edge.
	UserSettingsTable = "user_settings"
	// UserSettingsInverseTable is the table name for the UserSettings entity.
	// It exists in this package in order to avoid circular dependency with the "usersettings" package.
	UserSettingsInverseTable = "user_settings"
	// UserSettingsColumn is the table column denoting the user_settings relation/edge.
	UserSettingsColumn = "user_user_settings"
	// ActivationCodeTable is the table that holds the activation_code relation/edge.
	ActivationCodeTable = "activation_codes"
	// ActivationCodeInverseTable is the table name for the ActivationCode entity.
	// It exists in this package in order to avoid circular dependency with the "activationcode" package.
	ActivationCodeInverseTable = "activation_codes"
	// ActivationCodeColumn is the table column denoting the activation_code relation/edge.
	ActivationCodeColumn = "user_activation_code"
	// VerificationCodeTable is the table that holds the verification_code relation/edge.
	VerificationCodeTable = "verification_codes"
	// VerificationCodeInverseTable is the table name for the VerificationCode entity.
	// It exists in this package in order to avoid circular dependency with the "verificationcode" package.
	VerificationCodeInverseTable = "verification_codes"
	// VerificationCodeColumn is the table column denoting the verification_code relation/edge.
	VerificationCodeColumn = "user_verification_code"
	// SecondFactorCodeTable is the table that holds the second_factor_code relation/edge.
	SecondFactorCodeTable = "second_factor_codes"
	// SecondFactorCodeInverseTable is the table name for the SecondFactorCode entity.
	// It exists in this package in order to avoid circular dependency with the "secondfactorcode" package.
	SecondFactorCodeInverseTable = "second_factor_codes"
	// SecondFactorCodeColumn is the table column denoting the second_factor_code relation/edge.
	SecondFactorCodeColumn = "user_second_factor_code"
	// ResetCodeTable is the table that holds the reset_code relation/edge.
	ResetCodeTable = "reset_codes"
	// ResetCodeInverseTable is the table name for the ResetCode entity.
	// It exists in this package in order to avoid circular dependency with the "resetcode" package.
	ResetCodeInverseTable = "reset_codes"
	// ResetCodeColumn is the table column denoting the reset_code relation/edge.
	ResetCodeColumn = "user_reset_code"
	// UserDevicesTable is the table that holds the user_devices relation/edge.
	UserDevicesTable = "user_devices"
	// UserDevicesInverseTable is the table name for the UserDevice entity.
	// It exists in this package in order to avoid circular dependency with the "userdevice" package.
	UserDevicesInverseTable = "user_devices"
	// UserDevicesColumn is the table column denoting the user_devices relation/edge.
	UserDevicesColumn = "user_user_devices"
	// UserActionsTable is the table that holds the user_actions relation/edge. The primary key declared below.
	UserActionsTable = "user_user_actions"
	// UserActionsInverseTable is the table name for the UserAction entity.
	// It exists in this package in order to avoid circular dependency with the "useraction" package.
	UserActionsInverseTable = "user_actions"
	// UserRolesTable is the table that holds the user_roles relation/edge. The primary key declared below.
	UserRolesTable = "user_user_roles"
	// UserRolesInverseTable is the table name for the UserRole entity.
	// It exists in this package in order to avoid circular dependency with the "userrole" package.
	UserRolesInverseTable = "user_roles"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldMail,
	FieldPhone,
	FieldPassword,
	FieldActive,
	FieldVerified,
	FieldBlacklisted,
	FieldRemoved,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// UserActionsPrimaryKey and UserActionsColumn2 are the table columns denoting the
	// primary key for the user_actions relation (M2M).
	UserActionsPrimaryKey = []string{"user_id", "user_action_id"}
	// UserRolesPrimaryKey and UserRolesColumn2 are the table columns denoting the
	// primary key for the user_roles relation (M2M).
	UserRolesPrimaryKey = []string{"user_id", "user_role_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// MailValidator is a validator for the "mail" field. It is called by the builders before save.
	MailValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultVerified holds the default value on creation for the "verified" field.
	DefaultVerified bool
	// DefaultBlacklisted holds the default value on creation for the "blacklisted" field.
	DefaultBlacklisted bool
	// DefaultRemoved holds the default value on creation for the "removed" field.
	DefaultRemoved bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMail orders the results by the mail field.
func ByMail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMail, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByVerified orders the results by the verified field.
func ByVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerified, opts...).ToFunc()
}

// ByBlacklisted orders the results by the blacklisted field.
func ByBlacklisted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlacklisted, opts...).ToFunc()
}

// ByRemoved orders the results by the removed field.
func ByRemoved(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoved, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserDetailsField orders the results by user_details field.
func ByUserDetailsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserDetailsStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserSettingsField orders the results by user_settings field.
func ByUserSettingsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserSettingsStep(), sql.OrderByField(field, opts...))
	}
}

// ByActivationCodeField orders the results by activation_code field.
func ByActivationCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActivationCodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByVerificationCodeField orders the results by verification_code field.
func ByVerificationCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVerificationCodeStep(), sql.OrderByField(field, opts...))
	}
}

// BySecondFactorCodeField orders the results by second_factor_code field.
func BySecondFactorCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSecondFactorCodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByResetCodeField orders the results by reset_code field.
func ByResetCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResetCodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserDevicesCount orders the results by user_devices count.
func ByUserDevicesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserDevicesStep(), opts...)
	}
}

// ByUserDevices orders the results by user_devices terms.
func ByUserDevices(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserDevicesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserActionsCount orders the results by user_actions count.
func ByUserActionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserActionsStep(), opts...)
	}
}

// ByUserActions orders the results by user_actions terms.
func ByUserActions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserActionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserRolesCount orders the results by user_roles count.
func ByUserRolesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserRolesStep(), opts...)
	}
}

// ByUserRoles orders the results by user_roles terms.
func ByUserRoles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserRolesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserDetailsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserDetailsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, UserDetailsTable, UserDetailsColumn),
	)
}
func newUserSettingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserSettingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, UserSettingsTable, UserSettingsColumn),
	)
}
func newActivationCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActivationCodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, ActivationCodeTable, ActivationCodeColumn),
	)
}
func newVerificationCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VerificationCodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, VerificationCodeTable, VerificationCodeColumn),
	)
}
func newSecondFactorCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SecondFactorCodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, SecondFactorCodeTable, SecondFactorCodeColumn),
	)
}
func newResetCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResetCodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, ResetCodeTable, ResetCodeColumn),
	)
}
func newUserDevicesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserDevicesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserDevicesTable, UserDevicesColumn),
	)
}
func newUserActionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserActionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, UserActionsTable, UserActionsPrimaryKey...),
	)
}
func newUserRolesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserRolesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, UserRolesTable, UserRolesPrimaryKey...),
	)
}
