// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"users-service/app/models/ent/blacklistedtoken"
	"users-service/app/models/ent/predicate"
	"users-service/app/models/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlacklistedTokenQuery is the builder for querying BlacklistedToken entities.
type BlacklistedTokenQuery struct {
	config
	ctx        *QueryContext
	order      []blacklistedtoken.OrderOption
	inters     []Interceptor
	predicates []predicate.BlacklistedToken
	withOwner  *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BlacklistedTokenQuery builder.
func (btq *BlacklistedTokenQuery) Where(ps ...predicate.BlacklistedToken) *BlacklistedTokenQuery {
	btq.predicates = append(btq.predicates, ps...)
	return btq
}

// Limit the number of records to be returned by this query.
func (btq *BlacklistedTokenQuery) Limit(limit int) *BlacklistedTokenQuery {
	btq.ctx.Limit = &limit
	return btq
}

// Offset to start from.
func (btq *BlacklistedTokenQuery) Offset(offset int) *BlacklistedTokenQuery {
	btq.ctx.Offset = &offset
	return btq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (btq *BlacklistedTokenQuery) Unique(unique bool) *BlacklistedTokenQuery {
	btq.ctx.Unique = &unique
	return btq
}

// Order specifies how the records should be ordered.
func (btq *BlacklistedTokenQuery) Order(o ...blacklistedtoken.OrderOption) *BlacklistedTokenQuery {
	btq.order = append(btq.order, o...)
	return btq
}

// QueryOwner chains the current query on the "owner" edge.
func (btq *BlacklistedTokenQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: btq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := btq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := btq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blacklistedtoken.Table, blacklistedtoken.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, blacklistedtoken.OwnerTable, blacklistedtoken.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(btq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BlacklistedToken entity from the query.
// Returns a *NotFoundError when no BlacklistedToken was found.
func (btq *BlacklistedTokenQuery) First(ctx context.Context) (*BlacklistedToken, error) {
	nodes, err := btq.Limit(1).All(setContextOp(ctx, btq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{blacklistedtoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (btq *BlacklistedTokenQuery) FirstX(ctx context.Context) *BlacklistedToken {
	node, err := btq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BlacklistedToken ID from the query.
// Returns a *NotFoundError when no BlacklistedToken ID was found.
func (btq *BlacklistedTokenQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = btq.Limit(1).IDs(setContextOp(ctx, btq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{blacklistedtoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (btq *BlacklistedTokenQuery) FirstIDX(ctx context.Context) int {
	id, err := btq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BlacklistedToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BlacklistedToken entity is found.
// Returns a *NotFoundError when no BlacklistedToken entities are found.
func (btq *BlacklistedTokenQuery) Only(ctx context.Context) (*BlacklistedToken, error) {
	nodes, err := btq.Limit(2).All(setContextOp(ctx, btq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{blacklistedtoken.Label}
	default:
		return nil, &NotSingularError{blacklistedtoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (btq *BlacklistedTokenQuery) OnlyX(ctx context.Context) *BlacklistedToken {
	node, err := btq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BlacklistedToken ID in the query.
// Returns a *NotSingularError when more than one BlacklistedToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (btq *BlacklistedTokenQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = btq.Limit(2).IDs(setContextOp(ctx, btq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{blacklistedtoken.Label}
	default:
		err = &NotSingularError{blacklistedtoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (btq *BlacklistedTokenQuery) OnlyIDX(ctx context.Context) int {
	id, err := btq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BlacklistedTokens.
func (btq *BlacklistedTokenQuery) All(ctx context.Context) ([]*BlacklistedToken, error) {
	ctx = setContextOp(ctx, btq.ctx, ent.OpQueryAll)
	if err := btq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BlacklistedToken, *BlacklistedTokenQuery]()
	return withInterceptors[[]*BlacklistedToken](ctx, btq, qr, btq.inters)
}

// AllX is like All, but panics if an error occurs.
func (btq *BlacklistedTokenQuery) AllX(ctx context.Context) []*BlacklistedToken {
	nodes, err := btq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BlacklistedToken IDs.
func (btq *BlacklistedTokenQuery) IDs(ctx context.Context) (ids []int, err error) {
	if btq.ctx.Unique == nil && btq.path != nil {
		btq.Unique(true)
	}
	ctx = setContextOp(ctx, btq.ctx, ent.OpQueryIDs)
	if err = btq.Select(blacklistedtoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (btq *BlacklistedTokenQuery) IDsX(ctx context.Context) []int {
	ids, err := btq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (btq *BlacklistedTokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, btq.ctx, ent.OpQueryCount)
	if err := btq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, btq, querierCount[*BlacklistedTokenQuery](), btq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (btq *BlacklistedTokenQuery) CountX(ctx context.Context) int {
	count, err := btq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (btq *BlacklistedTokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, btq.ctx, ent.OpQueryExist)
	switch _, err := btq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (btq *BlacklistedTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := btq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BlacklistedTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (btq *BlacklistedTokenQuery) Clone() *BlacklistedTokenQuery {
	if btq == nil {
		return nil
	}
	return &BlacklistedTokenQuery{
		config:     btq.config,
		ctx:        btq.ctx.Clone(),
		order:      append([]blacklistedtoken.OrderOption{}, btq.order...),
		inters:     append([]Interceptor{}, btq.inters...),
		predicates: append([]predicate.BlacklistedToken{}, btq.predicates...),
		withOwner:  btq.withOwner.Clone(),
		// clone intermediate query.
		sql:  btq.sql.Clone(),
		path: btq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (btq *BlacklistedTokenQuery) WithOwner(opts ...func(*UserQuery)) *BlacklistedTokenQuery {
	query := (&UserClient{config: btq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	btq.withOwner = query
	return btq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Token string `json:"token"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BlacklistedToken.Query().
//		GroupBy(blacklistedtoken.FieldToken).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (btq *BlacklistedTokenQuery) GroupBy(field string, fields ...string) *BlacklistedTokenGroupBy {
	btq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BlacklistedTokenGroupBy{build: btq}
	grbuild.flds = &btq.ctx.Fields
	grbuild.label = blacklistedtoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Token string `json:"token"`
//	}
//
//	client.BlacklistedToken.Query().
//		Select(blacklistedtoken.FieldToken).
//		Scan(ctx, &v)
func (btq *BlacklistedTokenQuery) Select(fields ...string) *BlacklistedTokenSelect {
	btq.ctx.Fields = append(btq.ctx.Fields, fields...)
	sbuild := &BlacklistedTokenSelect{BlacklistedTokenQuery: btq}
	sbuild.label = blacklistedtoken.Label
	sbuild.flds, sbuild.scan = &btq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BlacklistedTokenSelect configured with the given aggregations.
func (btq *BlacklistedTokenQuery) Aggregate(fns ...AggregateFunc) *BlacklistedTokenSelect {
	return btq.Select().Aggregate(fns...)
}

func (btq *BlacklistedTokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range btq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, btq); err != nil {
				return err
			}
		}
	}
	for _, f := range btq.ctx.Fields {
		if !blacklistedtoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if btq.path != nil {
		prev, err := btq.path(ctx)
		if err != nil {
			return err
		}
		btq.sql = prev
	}
	return nil
}

func (btq *BlacklistedTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BlacklistedToken, error) {
	var (
		nodes       = []*BlacklistedToken{}
		withFKs     = btq.withFKs
		_spec       = btq.querySpec()
		loadedTypes = [1]bool{
			btq.withOwner != nil,
		}
	)
	if btq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, blacklistedtoken.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BlacklistedToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BlacklistedToken{config: btq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, btq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := btq.withOwner; query != nil {
		if err := btq.loadOwner(ctx, query, nodes, nil,
			func(n *BlacklistedToken, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (btq *BlacklistedTokenQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*BlacklistedToken, init func(*BlacklistedToken), assign func(*BlacklistedToken, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*BlacklistedToken)
	for i := range nodes {
		if nodes[i].blacklisted_token_owner == nil {
			continue
		}
		fk := *nodes[i].blacklisted_token_owner
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "blacklisted_token_owner" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (btq *BlacklistedTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := btq.querySpec()
	_spec.Node.Columns = btq.ctx.Fields
	if len(btq.ctx.Fields) > 0 {
		_spec.Unique = btq.ctx.Unique != nil && *btq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, btq.driver, _spec)
}

func (btq *BlacklistedTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(blacklistedtoken.Table, blacklistedtoken.Columns, sqlgraph.NewFieldSpec(blacklistedtoken.FieldID, field.TypeInt))
	_spec.From = btq.sql
	if unique := btq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if btq.path != nil {
		_spec.Unique = true
	}
	if fields := btq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blacklistedtoken.FieldID)
		for i := range fields {
			if fields[i] != blacklistedtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := btq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := btq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := btq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := btq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (btq *BlacklistedTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(btq.driver.Dialect())
	t1 := builder.Table(blacklistedtoken.Table)
	columns := btq.ctx.Fields
	if len(columns) == 0 {
		columns = blacklistedtoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if btq.sql != nil {
		selector = btq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if btq.ctx.Unique != nil && *btq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range btq.predicates {
		p(selector)
	}
	for _, p := range btq.order {
		p(selector)
	}
	if offset := btq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := btq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BlacklistedTokenGroupBy is the group-by builder for BlacklistedToken entities.
type BlacklistedTokenGroupBy struct {
	selector
	build *BlacklistedTokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (btgb *BlacklistedTokenGroupBy) Aggregate(fns ...AggregateFunc) *BlacklistedTokenGroupBy {
	btgb.fns = append(btgb.fns, fns...)
	return btgb
}

// Scan applies the selector query and scans the result into the given value.
func (btgb *BlacklistedTokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, btgb.build.ctx, ent.OpQueryGroupBy)
	if err := btgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlacklistedTokenQuery, *BlacklistedTokenGroupBy](ctx, btgb.build, btgb, btgb.build.inters, v)
}

func (btgb *BlacklistedTokenGroupBy) sqlScan(ctx context.Context, root *BlacklistedTokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(btgb.fns))
	for _, fn := range btgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*btgb.flds)+len(btgb.fns))
		for _, f := range *btgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*btgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := btgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BlacklistedTokenSelect is the builder for selecting fields of BlacklistedToken entities.
type BlacklistedTokenSelect struct {
	*BlacklistedTokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bts *BlacklistedTokenSelect) Aggregate(fns ...AggregateFunc) *BlacklistedTokenSelect {
	bts.fns = append(bts.fns, fns...)
	return bts
}

// Scan applies the selector query and scans the result into the given value.
func (bts *BlacklistedTokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bts.ctx, ent.OpQuerySelect)
	if err := bts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlacklistedTokenQuery, *BlacklistedTokenSelect](ctx, bts.BlacklistedTokenQuery, bts, bts.inters, v)
}

func (bts *BlacklistedTokenSelect) sqlScan(ctx context.Context, root *BlacklistedTokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bts.fns))
	for _, fn := range bts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
