// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"users-service/app/models/ent/blacklistedtoken"
	"users-service/app/models/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlacklistedTokenDelete is the builder for deleting a BlacklistedToken entity.
type BlacklistedTokenDelete struct {
	config
	hooks    []Hook
	mutation *BlacklistedTokenMutation
}

// Where appends a list predicates to the BlacklistedTokenDelete builder.
func (btd *BlacklistedTokenDelete) Where(ps ...predicate.BlacklistedToken) *BlacklistedTokenDelete {
	btd.mutation.Where(ps...)
	return btd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (btd *BlacklistedTokenDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, btd.sqlExec, btd.mutation, btd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (btd *BlacklistedTokenDelete) ExecX(ctx context.Context) int {
	n, err := btd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (btd *BlacklistedTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(blacklistedtoken.Table, sqlgraph.NewFieldSpec(blacklistedtoken.FieldID, field.TypeInt))
	if ps := btd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, btd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	btd.mutation.done = true
	return affected, err
}

// BlacklistedTokenDeleteOne is the builder for deleting a single BlacklistedToken entity.
type BlacklistedTokenDeleteOne struct {
	btd *BlacklistedTokenDelete
}

// Where appends a list predicates to the BlacklistedTokenDelete builder.
func (btdo *BlacklistedTokenDeleteOne) Where(ps ...predicate.BlacklistedToken) *BlacklistedTokenDeleteOne {
	btdo.btd.mutation.Where(ps...)
	return btdo
}

// Exec executes the deletion query.
func (btdo *BlacklistedTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := btdo.btd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{blacklistedtoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (btdo *BlacklistedTokenDeleteOne) ExecX(ctx context.Context) {
	if err := btdo.Exec(ctx); err != nil {
		panic(err)
	}
}
