// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"users-service/app/models/ent/entrepreneurdetails"
	"users-service/app/models/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntrepreneurDetailsDelete is the builder for deleting a EntrepreneurDetails entity.
type EntrepreneurDetailsDelete struct {
	config
	hooks    []Hook
	mutation *EntrepreneurDetailsMutation
}

// Where appends a list predicates to the EntrepreneurDetailsDelete builder.
func (edd *EntrepreneurDetailsDelete) Where(ps ...predicate.EntrepreneurDetails) *EntrepreneurDetailsDelete {
	edd.mutation.Where(ps...)
	return edd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (edd *EntrepreneurDetailsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, edd.sqlExec, edd.mutation, edd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (edd *EntrepreneurDetailsDelete) ExecX(ctx context.Context) int {
	n, err := edd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (edd *EntrepreneurDetailsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(entrepreneurdetails.Table, sqlgraph.NewFieldSpec(entrepreneurdetails.FieldID, field.TypeInt))
	if ps := edd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, edd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	edd.mutation.done = true
	return affected, err
}

// EntrepreneurDetailsDeleteOne is the builder for deleting a single EntrepreneurDetails entity.
type EntrepreneurDetailsDeleteOne struct {
	edd *EntrepreneurDetailsDelete
}

// Where appends a list predicates to the EntrepreneurDetailsDelete builder.
func (eddo *EntrepreneurDetailsDeleteOne) Where(ps ...predicate.EntrepreneurDetails) *EntrepreneurDetailsDeleteOne {
	eddo.edd.mutation.Where(ps...)
	return eddo
}

// Exec executes the deletion query.
func (eddo *EntrepreneurDetailsDeleteOne) Exec(ctx context.Context) error {
	n, err := eddo.edd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{entrepreneurdetails.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eddo *EntrepreneurDetailsDeleteOne) ExecX(ctx context.Context) {
	if err := eddo.Exec(ctx); err != nil {
		panic(err)
	}
}
