// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"users-service/app/models/ent/location"
	"users-service/app/models/ent/userdetails"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Location is the model entity for the Location schema.
type Location struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id"`
	// Country holds the value of the "country" field.
	Country string `json:"country"`
	// Province holds the value of the "province" field.
	Province string `json:"province"`
	// City holds the value of the "city" field.
	City string `json:"city"`
	// PostalCode holds the value of the "postal_code" field.
	PostalCode string `json:"postal_code"`
	// Street holds the value of the "street" field.
	Street string `json:"street"`
	// BuildingNumber holds the value of the "building_number" field.
	BuildingNumber int `json:"building_number"`
	// ApartmentNumber holds the value of the "apartment_number" field.
	ApartmentNumber int `json:"apartment_number"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LocationQuery when eager-loading is set.
	Edges                  LocationEdges `json:"edges"`
	user_details_locations *int
	selectValues           sql.SelectValues
}

// LocationEdges holds the relations/edges for other nodes in the graph.
type LocationEdges struct {
	// UserDetails holds the value of the user_details edge.
	UserDetails *UserDetails `json:"user_details"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserDetailsOrErr returns the UserDetails value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LocationEdges) UserDetailsOrErr() (*UserDetails, error) {
	if e.UserDetails != nil {
		return e.UserDetails, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: userdetails.Label}
	}
	return nil, &NotLoadedError{edge: "user_details"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Location) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case location.FieldID, location.FieldBuildingNumber, location.FieldApartmentNumber:
			values[i] = new(sql.NullInt64)
		case location.FieldCountry, location.FieldProvince, location.FieldCity, location.FieldPostalCode, location.FieldStreet:
			values[i] = new(sql.NullString)
		case location.FieldCreatedAt, location.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case location.ForeignKeys[0]: // user_details_locations
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Location fields.
func (l *Location) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case location.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			l.ID = int(value.Int64)
		case location.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				l.Country = value.String
			}
		case location.FieldProvince:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field province", values[i])
			} else if value.Valid {
				l.Province = value.String
			}
		case location.FieldCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field city", values[i])
			} else if value.Valid {
				l.City = value.String
			}
		case location.FieldPostalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field postal_code", values[i])
			} else if value.Valid {
				l.PostalCode = value.String
			}
		case location.FieldStreet:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field street", values[i])
			} else if value.Valid {
				l.Street = value.String
			}
		case location.FieldBuildingNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field building_number", values[i])
			} else if value.Valid {
				l.BuildingNumber = int(value.Int64)
			}
		case location.FieldApartmentNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field apartment_number", values[i])
			} else if value.Valid {
				l.ApartmentNumber = int(value.Int64)
			}
		case location.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				l.CreatedAt = value.Time
			}
		case location.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				l.UpdatedAt = value.Time
			}
		case location.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_details_locations", value)
			} else if value.Valid {
				l.user_details_locations = new(int)
				*l.user_details_locations = int(value.Int64)
			}
		default:
			l.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Location.
// This includes values selected through modifiers, order, etc.
func (l *Location) Value(name string) (ent.Value, error) {
	return l.selectValues.Get(name)
}

// QueryUserDetails queries the "user_details" edge of the Location entity.
func (l *Location) QueryUserDetails() *UserDetailsQuery {
	return NewLocationClient(l.config).QueryUserDetails(l)
}

// Update returns a builder for updating this Location.
// Note that you need to call Location.Unwrap() before calling this method if this Location
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *Location) Update() *LocationUpdateOne {
	return NewLocationClient(l.config).UpdateOne(l)
}

// Unwrap unwraps the Location entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *Location) Unwrap() *Location {
	_tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: Location is not a transactional entity")
	}
	l.config.driver = _tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *Location) String() string {
	var builder strings.Builder
	builder.WriteString("Location(")
	builder.WriteString(fmt.Sprintf("id=%v, ", l.ID))
	builder.WriteString("country=")
	builder.WriteString(l.Country)
	builder.WriteString(", ")
	builder.WriteString("province=")
	builder.WriteString(l.Province)
	builder.WriteString(", ")
	builder.WriteString("city=")
	builder.WriteString(l.City)
	builder.WriteString(", ")
	builder.WriteString("postal_code=")
	builder.WriteString(l.PostalCode)
	builder.WriteString(", ")
	builder.WriteString("street=")
	builder.WriteString(l.Street)
	builder.WriteString(", ")
	builder.WriteString("building_number=")
	builder.WriteString(fmt.Sprintf("%v", l.BuildingNumber))
	builder.WriteString(", ")
	builder.WriteString("apartment_number=")
	builder.WriteString(fmt.Sprintf("%v", l.ApartmentNumber))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(l.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(l.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Locations is a parsable slice of Location.
type Locations []*Location
