// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"users-service/app/models/ent/resetcode"
	"users-service/app/models/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ResetCode is the model entity for the ResetCode schema.
type ResetCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id"`
	// Code holds the value of the "code" field.
	Code string `json:"code"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResetCodeQuery when eager-loading is set.
	Edges           ResetCodeEdges `json:"edges"`
	user_reset_code *int
	selectValues    sql.SelectValues
}

// ResetCodeEdges holds the relations/edges for other nodes in the graph.
type ResetCodeEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ResetCodeEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResetCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resetcode.FieldID:
			values[i] = new(sql.NullInt64)
		case resetcode.FieldCode:
			values[i] = new(sql.NullString)
		case resetcode.FieldCreatedAt, resetcode.FieldUpdatedAt, resetcode.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case resetcode.ForeignKeys[0]: // user_reset_code
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResetCode fields.
func (rc *ResetCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resetcode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rc.ID = int(value.Int64)
		case resetcode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				rc.Code = value.String
			}
		case resetcode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rc.CreatedAt = value.Time
			}
		case resetcode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				rc.UpdatedAt = value.Time
			}
		case resetcode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				rc.ExpiresAt = value.Time
			}
		case resetcode.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_reset_code", value)
			} else if value.Valid {
				rc.user_reset_code = new(int)
				*rc.user_reset_code = int(value.Int64)
			}
		default:
			rc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResetCode.
// This includes values selected through modifiers, order, etc.
func (rc *ResetCode) Value(name string) (ent.Value, error) {
	return rc.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the ResetCode entity.
func (rc *ResetCode) QueryOwner() *UserQuery {
	return NewResetCodeClient(rc.config).QueryOwner(rc)
}

// Update returns a builder for updating this ResetCode.
// Note that you need to call ResetCode.Unwrap() before calling this method if this ResetCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (rc *ResetCode) Update() *ResetCodeUpdateOne {
	return NewResetCodeClient(rc.config).UpdateOne(rc)
}

// Unwrap unwraps the ResetCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rc *ResetCode) Unwrap() *ResetCode {
	_tx, ok := rc.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResetCode is not a transactional entity")
	}
	rc.config.driver = _tx.drv
	return rc
}

// String implements the fmt.Stringer.
func (rc *ResetCode) String() string {
	var builder strings.Builder
	builder.WriteString("ResetCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rc.ID))
	builder.WriteString("code=")
	builder.WriteString(rc.Code)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(rc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(rc.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(rc.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ResetCodes is a parsable slice of ResetCode.
type ResetCodes []*ResetCode
