// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"users-service/app/models/ent/rolepermission"
	"users-service/app/models/ent/userrole"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RolePermissionCreate is the builder for creating a RolePermission entity.
type RolePermissionCreate struct {
	config
	mutation *RolePermissionMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (rpc *RolePermissionCreate) SetName(s string) *RolePermissionCreate {
	rpc.mutation.SetName(s)
	return rpc
}

// SetView sets the "view" field.
func (rpc *RolePermissionCreate) SetView(b bool) *RolePermissionCreate {
	rpc.mutation.SetView(b)
	return rpc
}

// SetAdd sets the "add" field.
func (rpc *RolePermissionCreate) SetAdd(b bool) *RolePermissionCreate {
	rpc.mutation.SetAdd(b)
	return rpc
}

// SetEdit sets the "edit" field.
func (rpc *RolePermissionCreate) SetEdit(b bool) *RolePermissionCreate {
	rpc.mutation.SetEdit(b)
	return rpc
}

// SetDelete sets the "delete" field.
func (rpc *RolePermissionCreate) SetDelete(b bool) *RolePermissionCreate {
	rpc.mutation.SetDelete(b)
	return rpc
}

// SetCreatedAt sets the "created_at" field.
func (rpc *RolePermissionCreate) SetCreatedAt(t time.Time) *RolePermissionCreate {
	rpc.mutation.SetCreatedAt(t)
	return rpc
}

// SetUpdatedAt sets the "updated_at" field.
func (rpc *RolePermissionCreate) SetUpdatedAt(t time.Time) *RolePermissionCreate {
	rpc.mutation.SetUpdatedAt(t)
	return rpc
}

// SetID sets the "id" field.
func (rpc *RolePermissionCreate) SetID(i int) *RolePermissionCreate {
	rpc.mutation.SetID(i)
	return rpc
}

// AddUserRoleIDs adds the "user_role" edge to the UserRole entity by IDs.
func (rpc *RolePermissionCreate) AddUserRoleIDs(ids ...int) *RolePermissionCreate {
	rpc.mutation.AddUserRoleIDs(ids...)
	return rpc
}

// AddUserRole adds the "user_role" edges to the UserRole entity.
func (rpc *RolePermissionCreate) AddUserRole(u ...*UserRole) *RolePermissionCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return rpc.AddUserRoleIDs(ids...)
}

// Mutation returns the RolePermissionMutation object of the builder.
func (rpc *RolePermissionCreate) Mutation() *RolePermissionMutation {
	return rpc.mutation
}

// Save creates the RolePermission in the database.
func (rpc *RolePermissionCreate) Save(ctx context.Context) (*RolePermission, error) {
	return withHooks(ctx, rpc.sqlSave, rpc.mutation, rpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rpc *RolePermissionCreate) SaveX(ctx context.Context) *RolePermission {
	v, err := rpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rpc *RolePermissionCreate) Exec(ctx context.Context) error {
	_, err := rpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpc *RolePermissionCreate) ExecX(ctx context.Context) {
	if err := rpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rpc *RolePermissionCreate) check() error {
	if _, ok := rpc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RolePermission.name"`)}
	}
	if _, ok := rpc.mutation.View(); !ok {
		return &ValidationError{Name: "view", err: errors.New(`ent: missing required field "RolePermission.view"`)}
	}
	if _, ok := rpc.mutation.Add(); !ok {
		return &ValidationError{Name: "add", err: errors.New(`ent: missing required field "RolePermission.add"`)}
	}
	if _, ok := rpc.mutation.Edit(); !ok {
		return &ValidationError{Name: "edit", err: errors.New(`ent: missing required field "RolePermission.edit"`)}
	}
	if _, ok := rpc.mutation.Delete(); !ok {
		return &ValidationError{Name: "delete", err: errors.New(`ent: missing required field "RolePermission.delete"`)}
	}
	if _, ok := rpc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RolePermission.created_at"`)}
	}
	if _, ok := rpc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RolePermission.updated_at"`)}
	}
	return nil
}

func (rpc *RolePermissionCreate) sqlSave(ctx context.Context) (*RolePermission, error) {
	if err := rpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	rpc.mutation.id = &_node.ID
	rpc.mutation.done = true
	return _node, nil
}

func (rpc *RolePermissionCreate) createSpec() (*RolePermission, *sqlgraph.CreateSpec) {
	var (
		_node = &RolePermission{config: rpc.config}
		_spec = sqlgraph.NewCreateSpec(rolepermission.Table, sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt))
	)
	if id, ok := rpc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rpc.mutation.Name(); ok {
		_spec.SetField(rolepermission.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := rpc.mutation.View(); ok {
		_spec.SetField(rolepermission.FieldView, field.TypeBool, value)
		_node.View = value
	}
	if value, ok := rpc.mutation.Add(); ok {
		_spec.SetField(rolepermission.FieldAdd, field.TypeBool, value)
		_node.Add = value
	}
	if value, ok := rpc.mutation.Edit(); ok {
		_spec.SetField(rolepermission.FieldEdit, field.TypeBool, value)
		_node.Edit = value
	}
	if value, ok := rpc.mutation.Delete(); ok {
		_spec.SetField(rolepermission.FieldDelete, field.TypeBool, value)
		_node.Delete = value
	}
	if value, ok := rpc.mutation.CreatedAt(); ok {
		_spec.SetField(rolepermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rpc.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepermission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := rpc.mutation.UserRoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   rolepermission.UserRoleTable,
			Columns: rolepermission.UserRolePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RolePermissionCreateBulk is the builder for creating many RolePermission entities in bulk.
type RolePermissionCreateBulk struct {
	config
	err      error
	builders []*RolePermissionCreate
}

// Save creates the RolePermission entities in the database.
func (rpcb *RolePermissionCreateBulk) Save(ctx context.Context) ([]*RolePermission, error) {
	if rpcb.err != nil {
		return nil, rpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rpcb.builders))
	nodes := make([]*RolePermission, len(rpcb.builders))
	mutators := make([]Mutator, len(rpcb.builders))
	for i := range rpcb.builders {
		func(i int, root context.Context) {
			builder := rpcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RolePermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rpcb *RolePermissionCreateBulk) SaveX(ctx context.Context) []*RolePermission {
	v, err := rpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rpcb *RolePermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := rpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpcb *RolePermissionCreateBulk) ExecX(ctx context.Context) {
	if err := rpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
