// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"users-service/app/models/ent/predicate"
	"users-service/app/models/ent/secondfactorcode"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SecondFactorCodeDelete is the builder for deleting a SecondFactorCode entity.
type SecondFactorCodeDelete struct {
	config
	hooks    []Hook
	mutation *SecondFactorCodeMutation
}

// Where appends a list predicates to the SecondFactorCodeDelete builder.
func (sfcd *SecondFactorCodeDelete) Where(ps ...predicate.SecondFactorCode) *SecondFactorCodeDelete {
	sfcd.mutation.Where(ps...)
	return sfcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sfcd *SecondFactorCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sfcd.sqlExec, sfcd.mutation, sfcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sfcd *SecondFactorCodeDelete) ExecX(ctx context.Context) int {
	n, err := sfcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sfcd *SecondFactorCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(secondfactorcode.Table, sqlgraph.NewFieldSpec(secondfactorcode.FieldID, field.TypeInt))
	if ps := sfcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sfcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sfcd.mutation.done = true
	return affected, err
}

// SecondFactorCodeDeleteOne is the builder for deleting a single SecondFactorCode entity.
type SecondFactorCodeDeleteOne struct {
	sfcd *SecondFactorCodeDelete
}

// Where appends a list predicates to the SecondFactorCodeDelete builder.
func (sfcdo *SecondFactorCodeDeleteOne) Where(ps ...predicate.SecondFactorCode) *SecondFactorCodeDeleteOne {
	sfcdo.sfcd.mutation.Where(ps...)
	return sfcdo
}

// Exec executes the deletion query.
func (sfcdo *SecondFactorCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := sfcdo.sfcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{secondfactorcode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sfcdo *SecondFactorCodeDeleteOne) ExecX(ctx context.Context) {
	if err := sfcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
