// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"users-service/app/models/ent/secondfactorcode"
	"users-service/app/models/ent/user"
	"users-service/app/models/ent/userdevice"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SecondFactorCode is the model entity for the SecondFactorCode schema.
type SecondFactorCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id"`
	// Used holds the value of the "used" field.
	Used bool `json:"used"`
	// Code holds the value of the "code" field.
	Code string `json:"code"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SecondFactorCodeQuery when eager-loading is set.
	Edges                   SecondFactorCodeEdges `json:"edges"`
	user_second_factor_code *int
	selectValues            sql.SelectValues
}

// SecondFactorCodeEdges holds the relations/edges for other nodes in the graph.
type SecondFactorCodeEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner"`
	// TargetUserDevice holds the value of the target_user_device edge.
	TargetUserDevice *UserDevice `json:"target_user_device"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SecondFactorCodeEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// TargetUserDeviceOrErr returns the TargetUserDevice value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SecondFactorCodeEdges) TargetUserDeviceOrErr() (*UserDevice, error) {
	if e.TargetUserDevice != nil {
		return e.TargetUserDevice, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: userdevice.Label}
	}
	return nil, &NotLoadedError{edge: "target_user_device"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SecondFactorCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case secondfactorcode.FieldUsed:
			values[i] = new(sql.NullBool)
		case secondfactorcode.FieldID:
			values[i] = new(sql.NullInt64)
		case secondfactorcode.FieldCode:
			values[i] = new(sql.NullString)
		case secondfactorcode.FieldCreatedAt, secondfactorcode.FieldUpdatedAt, secondfactorcode.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case secondfactorcode.ForeignKeys[0]: // user_second_factor_code
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SecondFactorCode fields.
func (sfc *SecondFactorCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case secondfactorcode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sfc.ID = int(value.Int64)
		case secondfactorcode.FieldUsed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field used", values[i])
			} else if value.Valid {
				sfc.Used = value.Bool
			}
		case secondfactorcode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				sfc.Code = value.String
			}
		case secondfactorcode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sfc.CreatedAt = value.Time
			}
		case secondfactorcode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sfc.UpdatedAt = value.Time
			}
		case secondfactorcode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				sfc.ExpiresAt = value.Time
			}
		case secondfactorcode.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_second_factor_code", value)
			} else if value.Valid {
				sfc.user_second_factor_code = new(int)
				*sfc.user_second_factor_code = int(value.Int64)
			}
		default:
			sfc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SecondFactorCode.
// This includes values selected through modifiers, order, etc.
func (sfc *SecondFactorCode) Value(name string) (ent.Value, error) {
	return sfc.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the SecondFactorCode entity.
func (sfc *SecondFactorCode) QueryOwner() *UserQuery {
	return NewSecondFactorCodeClient(sfc.config).QueryOwner(sfc)
}

// QueryTargetUserDevice queries the "target_user_device" edge of the SecondFactorCode entity.
func (sfc *SecondFactorCode) QueryTargetUserDevice() *UserDeviceQuery {
	return NewSecondFactorCodeClient(sfc.config).QueryTargetUserDevice(sfc)
}

// Update returns a builder for updating this SecondFactorCode.
// Note that you need to call SecondFactorCode.Unwrap() before calling this method if this SecondFactorCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (sfc *SecondFactorCode) Update() *SecondFactorCodeUpdateOne {
	return NewSecondFactorCodeClient(sfc.config).UpdateOne(sfc)
}

// Unwrap unwraps the SecondFactorCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sfc *SecondFactorCode) Unwrap() *SecondFactorCode {
	_tx, ok := sfc.config.driver.(*txDriver)
	if !ok {
		panic("ent: SecondFactorCode is not a transactional entity")
	}
	sfc.config.driver = _tx.drv
	return sfc
}

// String implements the fmt.Stringer.
func (sfc *SecondFactorCode) String() string {
	var builder strings.Builder
	builder.WriteString("SecondFactorCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sfc.ID))
	builder.WriteString("used=")
	builder.WriteString(fmt.Sprintf("%v", sfc.Used))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(sfc.Code)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sfc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(sfc.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(sfc.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SecondFactorCodes is a parsable slice of SecondFactorCode.
type SecondFactorCodes []*SecondFactorCode
