// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"users-service/app/models/ent/predicate"
	"users-service/app/models/ent/secondfactorcode"
	"users-service/app/models/ent/user"
	"users-service/app/models/ent/userdevice"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SecondFactorCodeUpdate is the builder for updating SecondFactorCode entities.
type SecondFactorCodeUpdate struct {
	config
	hooks    []Hook
	mutation *SecondFactorCodeMutation
}

// Where appends a list predicates to the SecondFactorCodeUpdate builder.
func (sfcu *SecondFactorCodeUpdate) Where(ps ...predicate.SecondFactorCode) *SecondFactorCodeUpdate {
	sfcu.mutation.Where(ps...)
	return sfcu
}

// SetUsed sets the "used" field.
func (sfcu *SecondFactorCodeUpdate) SetUsed(b bool) *SecondFactorCodeUpdate {
	sfcu.mutation.SetUsed(b)
	return sfcu
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (sfcu *SecondFactorCodeUpdate) SetNillableUsed(b *bool) *SecondFactorCodeUpdate {
	if b != nil {
		sfcu.SetUsed(*b)
	}
	return sfcu
}

// SetCode sets the "code" field.
func (sfcu *SecondFactorCodeUpdate) SetCode(s string) *SecondFactorCodeUpdate {
	sfcu.mutation.SetCode(s)
	return sfcu
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (sfcu *SecondFactorCodeUpdate) SetNillableCode(s *string) *SecondFactorCodeUpdate {
	if s != nil {
		sfcu.SetCode(*s)
	}
	return sfcu
}

// SetCreatedAt sets the "created_at" field.
func (sfcu *SecondFactorCodeUpdate) SetCreatedAt(t time.Time) *SecondFactorCodeUpdate {
	sfcu.mutation.SetCreatedAt(t)
	return sfcu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sfcu *SecondFactorCodeUpdate) SetNillableCreatedAt(t *time.Time) *SecondFactorCodeUpdate {
	if t != nil {
		sfcu.SetCreatedAt(*t)
	}
	return sfcu
}

// SetUpdatedAt sets the "updated_at" field.
func (sfcu *SecondFactorCodeUpdate) SetUpdatedAt(t time.Time) *SecondFactorCodeUpdate {
	sfcu.mutation.SetUpdatedAt(t)
	return sfcu
}

// SetExpiresAt sets the "expires_at" field.
func (sfcu *SecondFactorCodeUpdate) SetExpiresAt(t time.Time) *SecondFactorCodeUpdate {
	sfcu.mutation.SetExpiresAt(t)
	return sfcu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (sfcu *SecondFactorCodeUpdate) SetNillableExpiresAt(t *time.Time) *SecondFactorCodeUpdate {
	if t != nil {
		sfcu.SetExpiresAt(*t)
	}
	return sfcu
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (sfcu *SecondFactorCodeUpdate) SetOwnerID(id int) *SecondFactorCodeUpdate {
	sfcu.mutation.SetOwnerID(id)
	return sfcu
}

// SetOwner sets the "owner" edge to the User entity.
func (sfcu *SecondFactorCodeUpdate) SetOwner(u *User) *SecondFactorCodeUpdate {
	return sfcu.SetOwnerID(u.ID)
}

// SetTargetUserDeviceID sets the "target_user_device" edge to the UserDevice entity by ID.
func (sfcu *SecondFactorCodeUpdate) SetTargetUserDeviceID(id int) *SecondFactorCodeUpdate {
	sfcu.mutation.SetTargetUserDeviceID(id)
	return sfcu
}

// SetTargetUserDevice sets the "target_user_device" edge to the UserDevice entity.
func (sfcu *SecondFactorCodeUpdate) SetTargetUserDevice(u *UserDevice) *SecondFactorCodeUpdate {
	return sfcu.SetTargetUserDeviceID(u.ID)
}

// Mutation returns the SecondFactorCodeMutation object of the builder.
func (sfcu *SecondFactorCodeUpdate) Mutation() *SecondFactorCodeMutation {
	return sfcu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (sfcu *SecondFactorCodeUpdate) ClearOwner() *SecondFactorCodeUpdate {
	sfcu.mutation.ClearOwner()
	return sfcu
}

// ClearTargetUserDevice clears the "target_user_device" edge to the UserDevice entity.
func (sfcu *SecondFactorCodeUpdate) ClearTargetUserDevice() *SecondFactorCodeUpdate {
	sfcu.mutation.ClearTargetUserDevice()
	return sfcu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sfcu *SecondFactorCodeUpdate) Save(ctx context.Context) (int, error) {
	sfcu.defaults()
	return withHooks(ctx, sfcu.sqlSave, sfcu.mutation, sfcu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sfcu *SecondFactorCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := sfcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sfcu *SecondFactorCodeUpdate) Exec(ctx context.Context) error {
	_, err := sfcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfcu *SecondFactorCodeUpdate) ExecX(ctx context.Context) {
	if err := sfcu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sfcu *SecondFactorCodeUpdate) defaults() {
	if _, ok := sfcu.mutation.UpdatedAt(); !ok {
		v := secondfactorcode.UpdateDefaultUpdatedAt()
		sfcu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sfcu *SecondFactorCodeUpdate) check() error {
	if sfcu.mutation.OwnerCleared() && len(sfcu.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SecondFactorCode.owner"`)
	}
	if sfcu.mutation.TargetUserDeviceCleared() && len(sfcu.mutation.TargetUserDeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SecondFactorCode.target_user_device"`)
	}
	return nil
}

func (sfcu *SecondFactorCodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := sfcu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(secondfactorcode.Table, secondfactorcode.Columns, sqlgraph.NewFieldSpec(secondfactorcode.FieldID, field.TypeInt))
	if ps := sfcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sfcu.mutation.Used(); ok {
		_spec.SetField(secondfactorcode.FieldUsed, field.TypeBool, value)
	}
	if value, ok := sfcu.mutation.Code(); ok {
		_spec.SetField(secondfactorcode.FieldCode, field.TypeString, value)
	}
	if value, ok := sfcu.mutation.CreatedAt(); ok {
		_spec.SetField(secondfactorcode.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := sfcu.mutation.UpdatedAt(); ok {
		_spec.SetField(secondfactorcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sfcu.mutation.ExpiresAt(); ok {
		_spec.SetField(secondfactorcode.FieldExpiresAt, field.TypeTime, value)
	}
	if sfcu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   secondfactorcode.OwnerTable,
			Columns: []string{secondfactorcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfcu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   secondfactorcode.OwnerTable,
			Columns: []string{secondfactorcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sfcu.mutation.TargetUserDeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   secondfactorcode.TargetUserDeviceTable,
			Columns: []string{secondfactorcode.TargetUserDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfcu.mutation.TargetUserDeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   secondfactorcode.TargetUserDeviceTable,
			Columns: []string{secondfactorcode.TargetUserDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sfcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{secondfactorcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sfcu.mutation.done = true
	return n, nil
}

// SecondFactorCodeUpdateOne is the builder for updating a single SecondFactorCode entity.
type SecondFactorCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SecondFactorCodeMutation
}

// SetUsed sets the "used" field.
func (sfcuo *SecondFactorCodeUpdateOne) SetUsed(b bool) *SecondFactorCodeUpdateOne {
	sfcuo.mutation.SetUsed(b)
	return sfcuo
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (sfcuo *SecondFactorCodeUpdateOne) SetNillableUsed(b *bool) *SecondFactorCodeUpdateOne {
	if b != nil {
		sfcuo.SetUsed(*b)
	}
	return sfcuo
}

// SetCode sets the "code" field.
func (sfcuo *SecondFactorCodeUpdateOne) SetCode(s string) *SecondFactorCodeUpdateOne {
	sfcuo.mutation.SetCode(s)
	return sfcuo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (sfcuo *SecondFactorCodeUpdateOne) SetNillableCode(s *string) *SecondFactorCodeUpdateOne {
	if s != nil {
		sfcuo.SetCode(*s)
	}
	return sfcuo
}

// SetCreatedAt sets the "created_at" field.
func (sfcuo *SecondFactorCodeUpdateOne) SetCreatedAt(t time.Time) *SecondFactorCodeUpdateOne {
	sfcuo.mutation.SetCreatedAt(t)
	return sfcuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sfcuo *SecondFactorCodeUpdateOne) SetNillableCreatedAt(t *time.Time) *SecondFactorCodeUpdateOne {
	if t != nil {
		sfcuo.SetCreatedAt(*t)
	}
	return sfcuo
}

// SetUpdatedAt sets the "updated_at" field.
func (sfcuo *SecondFactorCodeUpdateOne) SetUpdatedAt(t time.Time) *SecondFactorCodeUpdateOne {
	sfcuo.mutation.SetUpdatedAt(t)
	return sfcuo
}

// SetExpiresAt sets the "expires_at" field.
func (sfcuo *SecondFactorCodeUpdateOne) SetExpiresAt(t time.Time) *SecondFactorCodeUpdateOne {
	sfcuo.mutation.SetExpiresAt(t)
	return sfcuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (sfcuo *SecondFactorCodeUpdateOne) SetNillableExpiresAt(t *time.Time) *SecondFactorCodeUpdateOne {
	if t != nil {
		sfcuo.SetExpiresAt(*t)
	}
	return sfcuo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (sfcuo *SecondFactorCodeUpdateOne) SetOwnerID(id int) *SecondFactorCodeUpdateOne {
	sfcuo.mutation.SetOwnerID(id)
	return sfcuo
}

// SetOwner sets the "owner" edge to the User entity.
func (sfcuo *SecondFactorCodeUpdateOne) SetOwner(u *User) *SecondFactorCodeUpdateOne {
	return sfcuo.SetOwnerID(u.ID)
}

// SetTargetUserDeviceID sets the "target_user_device" edge to the UserDevice entity by ID.
func (sfcuo *SecondFactorCodeUpdateOne) SetTargetUserDeviceID(id int) *SecondFactorCodeUpdateOne {
	sfcuo.mutation.SetTargetUserDeviceID(id)
	return sfcuo
}

// SetTargetUserDevice sets the "target_user_device" edge to the UserDevice entity.
func (sfcuo *SecondFactorCodeUpdateOne) SetTargetUserDevice(u *UserDevice) *SecondFactorCodeUpdateOne {
	return sfcuo.SetTargetUserDeviceID(u.ID)
}

// Mutation returns the SecondFactorCodeMutation object of the builder.
func (sfcuo *SecondFactorCodeUpdateOne) Mutation() *SecondFactorCodeMutation {
	return sfcuo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (sfcuo *SecondFactorCodeUpdateOne) ClearOwner() *SecondFactorCodeUpdateOne {
	sfcuo.mutation.ClearOwner()
	return sfcuo
}

// ClearTargetUserDevice clears the "target_user_device" edge to the UserDevice entity.
func (sfcuo *SecondFactorCodeUpdateOne) ClearTargetUserDevice() *SecondFactorCodeUpdateOne {
	sfcuo.mutation.ClearTargetUserDevice()
	return sfcuo
}

// Where appends a list predicates to the SecondFactorCodeUpdate builder.
func (sfcuo *SecondFactorCodeUpdateOne) Where(ps ...predicate.SecondFactorCode) *SecondFactorCodeUpdateOne {
	sfcuo.mutation.Where(ps...)
	return sfcuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sfcuo *SecondFactorCodeUpdateOne) Select(field string, fields ...string) *SecondFactorCodeUpdateOne {
	sfcuo.fields = append([]string{field}, fields...)
	return sfcuo
}

// Save executes the query and returns the updated SecondFactorCode entity.
func (sfcuo *SecondFactorCodeUpdateOne) Save(ctx context.Context) (*SecondFactorCode, error) {
	sfcuo.defaults()
	return withHooks(ctx, sfcuo.sqlSave, sfcuo.mutation, sfcuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sfcuo *SecondFactorCodeUpdateOne) SaveX(ctx context.Context) *SecondFactorCode {
	node, err := sfcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sfcuo *SecondFactorCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := sfcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sfcuo *SecondFactorCodeUpdateOne) ExecX(ctx context.Context) {
	if err := sfcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sfcuo *SecondFactorCodeUpdateOne) defaults() {
	if _, ok := sfcuo.mutation.UpdatedAt(); !ok {
		v := secondfactorcode.UpdateDefaultUpdatedAt()
		sfcuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sfcuo *SecondFactorCodeUpdateOne) check() error {
	if sfcuo.mutation.OwnerCleared() && len(sfcuo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SecondFactorCode.owner"`)
	}
	if sfcuo.mutation.TargetUserDeviceCleared() && len(sfcuo.mutation.TargetUserDeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SecondFactorCode.target_user_device"`)
	}
	return nil
}

func (sfcuo *SecondFactorCodeUpdateOne) sqlSave(ctx context.Context) (_node *SecondFactorCode, err error) {
	if err := sfcuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(secondfactorcode.Table, secondfactorcode.Columns, sqlgraph.NewFieldSpec(secondfactorcode.FieldID, field.TypeInt))
	id, ok := sfcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SecondFactorCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sfcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, secondfactorcode.FieldID)
		for _, f := range fields {
			if !secondfactorcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != secondfactorcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sfcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sfcuo.mutation.Used(); ok {
		_spec.SetField(secondfactorcode.FieldUsed, field.TypeBool, value)
	}
	if value, ok := sfcuo.mutation.Code(); ok {
		_spec.SetField(secondfactorcode.FieldCode, field.TypeString, value)
	}
	if value, ok := sfcuo.mutation.CreatedAt(); ok {
		_spec.SetField(secondfactorcode.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := sfcuo.mutation.UpdatedAt(); ok {
		_spec.SetField(secondfactorcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sfcuo.mutation.ExpiresAt(); ok {
		_spec.SetField(secondfactorcode.FieldExpiresAt, field.TypeTime, value)
	}
	if sfcuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   secondfactorcode.OwnerTable,
			Columns: []string{secondfactorcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfcuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   secondfactorcode.OwnerTable,
			Columns: []string{secondfactorcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if sfcuo.mutation.TargetUserDeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   secondfactorcode.TargetUserDeviceTable,
			Columns: []string{secondfactorcode.TargetUserDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sfcuo.mutation.TargetUserDeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   secondfactorcode.TargetUserDeviceTable,
			Columns: []string{secondfactorcode.TargetUserDeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SecondFactorCode{config: sfcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sfcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{secondfactorcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sfcuo.mutation.done = true
	return _node, nil
}
