// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"users-service/app/models/ent/predicate"
	"users-service/app/models/ent/secondfactorcode"
	"users-service/app/models/ent/user"
	"users-service/app/models/ent/userdevice"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SecondFactorCodeQuery is the builder for querying SecondFactorCode entities.
type SecondFactorCodeQuery struct {
	config
	ctx                  *QueryContext
	order                []secondfactorcode.OrderOption
	inters               []Interceptor
	predicates           []predicate.SecondFactorCode
	withOwner            *UserQuery
	withTargetUserDevice *UserDeviceQuery
	withFKs              bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SecondFactorCodeQuery builder.
func (sfcq *SecondFactorCodeQuery) Where(ps ...predicate.SecondFactorCode) *SecondFactorCodeQuery {
	sfcq.predicates = append(sfcq.predicates, ps...)
	return sfcq
}

// Limit the number of records to be returned by this query.
func (sfcq *SecondFactorCodeQuery) Limit(limit int) *SecondFactorCodeQuery {
	sfcq.ctx.Limit = &limit
	return sfcq
}

// Offset to start from.
func (sfcq *SecondFactorCodeQuery) Offset(offset int) *SecondFactorCodeQuery {
	sfcq.ctx.Offset = &offset
	return sfcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sfcq *SecondFactorCodeQuery) Unique(unique bool) *SecondFactorCodeQuery {
	sfcq.ctx.Unique = &unique
	return sfcq
}

// Order specifies how the records should be ordered.
func (sfcq *SecondFactorCodeQuery) Order(o ...secondfactorcode.OrderOption) *SecondFactorCodeQuery {
	sfcq.order = append(sfcq.order, o...)
	return sfcq
}

// QueryOwner chains the current query on the "owner" edge.
func (sfcq *SecondFactorCodeQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: sfcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sfcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sfcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(secondfactorcode.Table, secondfactorcode.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, secondfactorcode.OwnerTable, secondfactorcode.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(sfcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTargetUserDevice chains the current query on the "target_user_device" edge.
func (sfcq *SecondFactorCodeQuery) QueryTargetUserDevice() *UserDeviceQuery {
	query := (&UserDeviceClient{config: sfcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sfcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sfcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(secondfactorcode.Table, secondfactorcode.FieldID, selector),
			sqlgraph.To(userdevice.Table, userdevice.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, secondfactorcode.TargetUserDeviceTable, secondfactorcode.TargetUserDeviceColumn),
		)
		fromU = sqlgraph.SetNeighbors(sfcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SecondFactorCode entity from the query.
// Returns a *NotFoundError when no SecondFactorCode was found.
func (sfcq *SecondFactorCodeQuery) First(ctx context.Context) (*SecondFactorCode, error) {
	nodes, err := sfcq.Limit(1).All(setContextOp(ctx, sfcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{secondfactorcode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sfcq *SecondFactorCodeQuery) FirstX(ctx context.Context) *SecondFactorCode {
	node, err := sfcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SecondFactorCode ID from the query.
// Returns a *NotFoundError when no SecondFactorCode ID was found.
func (sfcq *SecondFactorCodeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sfcq.Limit(1).IDs(setContextOp(ctx, sfcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{secondfactorcode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sfcq *SecondFactorCodeQuery) FirstIDX(ctx context.Context) int {
	id, err := sfcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SecondFactorCode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SecondFactorCode entity is found.
// Returns a *NotFoundError when no SecondFactorCode entities are found.
func (sfcq *SecondFactorCodeQuery) Only(ctx context.Context) (*SecondFactorCode, error) {
	nodes, err := sfcq.Limit(2).All(setContextOp(ctx, sfcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{secondfactorcode.Label}
	default:
		return nil, &NotSingularError{secondfactorcode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sfcq *SecondFactorCodeQuery) OnlyX(ctx context.Context) *SecondFactorCode {
	node, err := sfcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SecondFactorCode ID in the query.
// Returns a *NotSingularError when more than one SecondFactorCode ID is found.
// Returns a *NotFoundError when no entities are found.
func (sfcq *SecondFactorCodeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sfcq.Limit(2).IDs(setContextOp(ctx, sfcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{secondfactorcode.Label}
	default:
		err = &NotSingularError{secondfactorcode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sfcq *SecondFactorCodeQuery) OnlyIDX(ctx context.Context) int {
	id, err := sfcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SecondFactorCodes.
func (sfcq *SecondFactorCodeQuery) All(ctx context.Context) ([]*SecondFactorCode, error) {
	ctx = setContextOp(ctx, sfcq.ctx, ent.OpQueryAll)
	if err := sfcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SecondFactorCode, *SecondFactorCodeQuery]()
	return withInterceptors[[]*SecondFactorCode](ctx, sfcq, qr, sfcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sfcq *SecondFactorCodeQuery) AllX(ctx context.Context) []*SecondFactorCode {
	nodes, err := sfcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SecondFactorCode IDs.
func (sfcq *SecondFactorCodeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sfcq.ctx.Unique == nil && sfcq.path != nil {
		sfcq.Unique(true)
	}
	ctx = setContextOp(ctx, sfcq.ctx, ent.OpQueryIDs)
	if err = sfcq.Select(secondfactorcode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sfcq *SecondFactorCodeQuery) IDsX(ctx context.Context) []int {
	ids, err := sfcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sfcq *SecondFactorCodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sfcq.ctx, ent.OpQueryCount)
	if err := sfcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sfcq, querierCount[*SecondFactorCodeQuery](), sfcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sfcq *SecondFactorCodeQuery) CountX(ctx context.Context) int {
	count, err := sfcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sfcq *SecondFactorCodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sfcq.ctx, ent.OpQueryExist)
	switch _, err := sfcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sfcq *SecondFactorCodeQuery) ExistX(ctx context.Context) bool {
	exist, err := sfcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SecondFactorCodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sfcq *SecondFactorCodeQuery) Clone() *SecondFactorCodeQuery {
	if sfcq == nil {
		return nil
	}
	return &SecondFactorCodeQuery{
		config:               sfcq.config,
		ctx:                  sfcq.ctx.Clone(),
		order:                append([]secondfactorcode.OrderOption{}, sfcq.order...),
		inters:               append([]Interceptor{}, sfcq.inters...),
		predicates:           append([]predicate.SecondFactorCode{}, sfcq.predicates...),
		withOwner:            sfcq.withOwner.Clone(),
		withTargetUserDevice: sfcq.withTargetUserDevice.Clone(),
		// clone intermediate query.
		sql:  sfcq.sql.Clone(),
		path: sfcq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (sfcq *SecondFactorCodeQuery) WithOwner(opts ...func(*UserQuery)) *SecondFactorCodeQuery {
	query := (&UserClient{config: sfcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sfcq.withOwner = query
	return sfcq
}

// WithTargetUserDevice tells the query-builder to eager-load the nodes that are connected to
// the "target_user_device" edge. The optional arguments are used to configure the query builder of the edge.
func (sfcq *SecondFactorCodeQuery) WithTargetUserDevice(opts ...func(*UserDeviceQuery)) *SecondFactorCodeQuery {
	query := (&UserDeviceClient{config: sfcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sfcq.withTargetUserDevice = query
	return sfcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Used bool `json:"used"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SecondFactorCode.Query().
//		GroupBy(secondfactorcode.FieldUsed).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sfcq *SecondFactorCodeQuery) GroupBy(field string, fields ...string) *SecondFactorCodeGroupBy {
	sfcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SecondFactorCodeGroupBy{build: sfcq}
	grbuild.flds = &sfcq.ctx.Fields
	grbuild.label = secondfactorcode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Used bool `json:"used"`
//	}
//
//	client.SecondFactorCode.Query().
//		Select(secondfactorcode.FieldUsed).
//		Scan(ctx, &v)
func (sfcq *SecondFactorCodeQuery) Select(fields ...string) *SecondFactorCodeSelect {
	sfcq.ctx.Fields = append(sfcq.ctx.Fields, fields...)
	sbuild := &SecondFactorCodeSelect{SecondFactorCodeQuery: sfcq}
	sbuild.label = secondfactorcode.Label
	sbuild.flds, sbuild.scan = &sfcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SecondFactorCodeSelect configured with the given aggregations.
func (sfcq *SecondFactorCodeQuery) Aggregate(fns ...AggregateFunc) *SecondFactorCodeSelect {
	return sfcq.Select().Aggregate(fns...)
}

func (sfcq *SecondFactorCodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sfcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sfcq); err != nil {
				return err
			}
		}
	}
	for _, f := range sfcq.ctx.Fields {
		if !secondfactorcode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sfcq.path != nil {
		prev, err := sfcq.path(ctx)
		if err != nil {
			return err
		}
		sfcq.sql = prev
	}
	return nil
}

func (sfcq *SecondFactorCodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SecondFactorCode, error) {
	var (
		nodes       = []*SecondFactorCode{}
		withFKs     = sfcq.withFKs
		_spec       = sfcq.querySpec()
		loadedTypes = [2]bool{
			sfcq.withOwner != nil,
			sfcq.withTargetUserDevice != nil,
		}
	)
	if sfcq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, secondfactorcode.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SecondFactorCode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SecondFactorCode{config: sfcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sfcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sfcq.withOwner; query != nil {
		if err := sfcq.loadOwner(ctx, query, nodes, nil,
			func(n *SecondFactorCode, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := sfcq.withTargetUserDevice; query != nil {
		if err := sfcq.loadTargetUserDevice(ctx, query, nodes, nil,
			func(n *SecondFactorCode, e *UserDevice) { n.Edges.TargetUserDevice = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sfcq *SecondFactorCodeQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*SecondFactorCode, init func(*SecondFactorCode), assign func(*SecondFactorCode, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SecondFactorCode)
	for i := range nodes {
		if nodes[i].user_second_factor_code == nil {
			continue
		}
		fk := *nodes[i].user_second_factor_code
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_second_factor_code" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (sfcq *SecondFactorCodeQuery) loadTargetUserDevice(ctx context.Context, query *UserDeviceQuery, nodes []*SecondFactorCode, init func(*SecondFactorCode), assign func(*SecondFactorCode, *UserDevice)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*SecondFactorCode)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.UserDevice(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(secondfactorcode.TargetUserDeviceColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.second_factor_code_target_user_device
		if fk == nil {
			return fmt.Errorf(`foreign-key "second_factor_code_target_user_device" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "second_factor_code_target_user_device" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (sfcq *SecondFactorCodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sfcq.querySpec()
	_spec.Node.Columns = sfcq.ctx.Fields
	if len(sfcq.ctx.Fields) > 0 {
		_spec.Unique = sfcq.ctx.Unique != nil && *sfcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sfcq.driver, _spec)
}

func (sfcq *SecondFactorCodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(secondfactorcode.Table, secondfactorcode.Columns, sqlgraph.NewFieldSpec(secondfactorcode.FieldID, field.TypeInt))
	_spec.From = sfcq.sql
	if unique := sfcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sfcq.path != nil {
		_spec.Unique = true
	}
	if fields := sfcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, secondfactorcode.FieldID)
		for i := range fields {
			if fields[i] != secondfactorcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sfcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sfcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sfcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sfcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sfcq *SecondFactorCodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sfcq.driver.Dialect())
	t1 := builder.Table(secondfactorcode.Table)
	columns := sfcq.ctx.Fields
	if len(columns) == 0 {
		columns = secondfactorcode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sfcq.sql != nil {
		selector = sfcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sfcq.ctx.Unique != nil && *sfcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sfcq.predicates {
		p(selector)
	}
	for _, p := range sfcq.order {
		p(selector)
	}
	if offset := sfcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sfcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SecondFactorCodeGroupBy is the group-by builder for SecondFactorCode entities.
type SecondFactorCodeGroupBy struct {
	selector
	build *SecondFactorCodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sfcgb *SecondFactorCodeGroupBy) Aggregate(fns ...AggregateFunc) *SecondFactorCodeGroupBy {
	sfcgb.fns = append(sfcgb.fns, fns...)
	return sfcgb
}

// Scan applies the selector query and scans the result into the given value.
func (sfcgb *SecondFactorCodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sfcgb.build.ctx, ent.OpQueryGroupBy)
	if err := sfcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SecondFactorCodeQuery, *SecondFactorCodeGroupBy](ctx, sfcgb.build, sfcgb, sfcgb.build.inters, v)
}

func (sfcgb *SecondFactorCodeGroupBy) sqlScan(ctx context.Context, root *SecondFactorCodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sfcgb.fns))
	for _, fn := range sfcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sfcgb.flds)+len(sfcgb.fns))
		for _, f := range *sfcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sfcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sfcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SecondFactorCodeSelect is the builder for selecting fields of SecondFactorCode entities.
type SecondFactorCodeSelect struct {
	*SecondFactorCodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sfcs *SecondFactorCodeSelect) Aggregate(fns ...AggregateFunc) *SecondFactorCodeSelect {
	sfcs.fns = append(sfcs.fns, fns...)
	return sfcs
}

// Scan applies the selector query and scans the result into the given value.
func (sfcs *SecondFactorCodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sfcs.ctx, ent.OpQuerySelect)
	if err := sfcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SecondFactorCodeQuery, *SecondFactorCodeSelect](ctx, sfcs.SecondFactorCodeQuery, sfcs, sfcs.inters, v)
}

func (sfcs *SecondFactorCodeSelect) sqlScan(ctx context.Context, root *SecondFactorCodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sfcs.fns))
	for _, fn := range sfcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sfcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sfcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
