// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"users-service/app/models/ent/activationcode"
	"users-service/app/models/ent/blacklistedtoken"
	"users-service/app/models/ent/predicate"
	"users-service/app/models/ent/resetcode"
	"users-service/app/models/ent/secondfactorcode"
	"users-service/app/models/ent/user"
	"users-service/app/models/ent/useraction"
	"users-service/app/models/ent/userdetails"
	"users-service/app/models/ent/userdevice"
	"users-service/app/models/ent/userrole"
	"users-service/app/models/ent/usersettings"
	"users-service/app/models/ent/verificationcode"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetMail sets the "mail" field.
func (uu *UserUpdate) SetMail(s string) *UserUpdate {
	uu.mutation.SetMail(s)
	return uu
}

// SetNillableMail sets the "mail" field if the given value is not nil.
func (uu *UserUpdate) SetNillableMail(s *string) *UserUpdate {
	if s != nil {
		uu.SetMail(*s)
	}
	return uu
}

// SetPhone sets the "phone" field.
func (uu *UserUpdate) SetPhone(s string) *UserUpdate {
	uu.mutation.SetPhone(s)
	return uu
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (uu *UserUpdate) SetNillablePhone(s *string) *UserUpdate {
	if s != nil {
		uu.SetPhone(*s)
	}
	return uu
}

// ClearPhone clears the value of the "phone" field.
func (uu *UserUpdate) ClearPhone() *UserUpdate {
	uu.mutation.ClearPhone()
	return uu
}

// SetPassword sets the "password" field.
func (uu *UserUpdate) SetPassword(s string) *UserUpdate {
	uu.mutation.SetPassword(s)
	return uu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uu *UserUpdate) SetNillablePassword(s *string) *UserUpdate {
	if s != nil {
		uu.SetPassword(*s)
	}
	return uu
}

// SetActive sets the "active" field.
func (uu *UserUpdate) SetActive(b bool) *UserUpdate {
	uu.mutation.SetActive(b)
	return uu
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (uu *UserUpdate) SetNillableActive(b *bool) *UserUpdate {
	if b != nil {
		uu.SetActive(*b)
	}
	return uu
}

// SetVerified sets the "verified" field.
func (uu *UserUpdate) SetVerified(b bool) *UserUpdate {
	uu.mutation.SetVerified(b)
	return uu
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (uu *UserUpdate) SetNillableVerified(b *bool) *UserUpdate {
	if b != nil {
		uu.SetVerified(*b)
	}
	return uu
}

// SetBlacklisted sets the "blacklisted" field.
func (uu *UserUpdate) SetBlacklisted(b bool) *UserUpdate {
	uu.mutation.SetBlacklisted(b)
	return uu
}

// SetNillableBlacklisted sets the "blacklisted" field if the given value is not nil.
func (uu *UserUpdate) SetNillableBlacklisted(b *bool) *UserUpdate {
	if b != nil {
		uu.SetBlacklisted(*b)
	}
	return uu
}

// SetRemoved sets the "removed" field.
func (uu *UserUpdate) SetRemoved(b bool) *UserUpdate {
	uu.mutation.SetRemoved(b)
	return uu
}

// SetNillableRemoved sets the "removed" field if the given value is not nil.
func (uu *UserUpdate) SetNillableRemoved(b *bool) *UserUpdate {
	if b != nil {
		uu.SetRemoved(*b)
	}
	return uu
}

// SetUpdatedAt sets the "updated_at" field.
func (uu *UserUpdate) SetUpdatedAt(t time.Time) *UserUpdate {
	uu.mutation.SetUpdatedAt(t)
	return uu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uu *UserUpdate) SetNillableUpdatedAt(t *time.Time) *UserUpdate {
	if t != nil {
		uu.SetUpdatedAt(*t)
	}
	return uu
}

// SetSubscriptionIds sets the "subscription_ids" field.
func (uu *UserUpdate) SetSubscriptionIds(i []int) *UserUpdate {
	uu.mutation.SetSubscriptionIds(i)
	return uu
}

// AppendSubscriptionIds appends i to the "subscription_ids" field.
func (uu *UserUpdate) AppendSubscriptionIds(i []int) *UserUpdate {
	uu.mutation.AppendSubscriptionIds(i)
	return uu
}

// SetTeamIds sets the "team_ids" field.
func (uu *UserUpdate) SetTeamIds(i []int) *UserUpdate {
	uu.mutation.SetTeamIds(i)
	return uu
}

// AppendTeamIds appends i to the "team_ids" field.
func (uu *UserUpdate) AppendTeamIds(i []int) *UserUpdate {
	uu.mutation.AppendTeamIds(i)
	return uu
}

// SetOrganizationIds sets the "organization_ids" field.
func (uu *UserUpdate) SetOrganizationIds(i []int) *UserUpdate {
	uu.mutation.SetOrganizationIds(i)
	return uu
}

// AppendOrganizationIds appends i to the "organization_ids" field.
func (uu *UserUpdate) AppendOrganizationIds(i []int) *UserUpdate {
	uu.mutation.AppendOrganizationIds(i)
	return uu
}

// SetUserDetailsID sets the "user_details" edge to the UserDetails entity by ID.
func (uu *UserUpdate) SetUserDetailsID(id int) *UserUpdate {
	uu.mutation.SetUserDetailsID(id)
	return uu
}

// SetNillableUserDetailsID sets the "user_details" edge to the UserDetails entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableUserDetailsID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetUserDetailsID(*id)
	}
	return uu
}

// SetUserDetails sets the "user_details" edge to the UserDetails entity.
func (uu *UserUpdate) SetUserDetails(u *UserDetails) *UserUpdate {
	return uu.SetUserDetailsID(u.ID)
}

// SetUserSettingsID sets the "user_settings" edge to the UserSettings entity by ID.
func (uu *UserUpdate) SetUserSettingsID(id int) *UserUpdate {
	uu.mutation.SetUserSettingsID(id)
	return uu
}

// SetNillableUserSettingsID sets the "user_settings" edge to the UserSettings entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableUserSettingsID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetUserSettingsID(*id)
	}
	return uu
}

// SetUserSettings sets the "user_settings" edge to the UserSettings entity.
func (uu *UserUpdate) SetUserSettings(u *UserSettings) *UserUpdate {
	return uu.SetUserSettingsID(u.ID)
}

// SetActivationCodeID sets the "activation_code" edge to the ActivationCode entity by ID.
func (uu *UserUpdate) SetActivationCodeID(id int) *UserUpdate {
	uu.mutation.SetActivationCodeID(id)
	return uu
}

// SetNillableActivationCodeID sets the "activation_code" edge to the ActivationCode entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableActivationCodeID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetActivationCodeID(*id)
	}
	return uu
}

// SetActivationCode sets the "activation_code" edge to the ActivationCode entity.
func (uu *UserUpdate) SetActivationCode(a *ActivationCode) *UserUpdate {
	return uu.SetActivationCodeID(a.ID)
}

// SetVerificationCodeID sets the "verification_code" edge to the VerificationCode entity by ID.
func (uu *UserUpdate) SetVerificationCodeID(id int) *UserUpdate {
	uu.mutation.SetVerificationCodeID(id)
	return uu
}

// SetNillableVerificationCodeID sets the "verification_code" edge to the VerificationCode entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableVerificationCodeID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetVerificationCodeID(*id)
	}
	return uu
}

// SetVerificationCode sets the "verification_code" edge to the VerificationCode entity.
func (uu *UserUpdate) SetVerificationCode(v *VerificationCode) *UserUpdate {
	return uu.SetVerificationCodeID(v.ID)
}

// SetSecondFactorCodeID sets the "second_factor_code" edge to the SecondFactorCode entity by ID.
func (uu *UserUpdate) SetSecondFactorCodeID(id int) *UserUpdate {
	uu.mutation.SetSecondFactorCodeID(id)
	return uu
}

// SetNillableSecondFactorCodeID sets the "second_factor_code" edge to the SecondFactorCode entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableSecondFactorCodeID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetSecondFactorCodeID(*id)
	}
	return uu
}

// SetSecondFactorCode sets the "second_factor_code" edge to the SecondFactorCode entity.
func (uu *UserUpdate) SetSecondFactorCode(s *SecondFactorCode) *UserUpdate {
	return uu.SetSecondFactorCodeID(s.ID)
}

// SetResetCodeID sets the "reset_code" edge to the ResetCode entity by ID.
func (uu *UserUpdate) SetResetCodeID(id int) *UserUpdate {
	uu.mutation.SetResetCodeID(id)
	return uu
}

// SetNillableResetCodeID sets the "reset_code" edge to the ResetCode entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableResetCodeID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetResetCodeID(*id)
	}
	return uu
}

// SetResetCode sets the "reset_code" edge to the ResetCode entity.
func (uu *UserUpdate) SetResetCode(r *ResetCode) *UserUpdate {
	return uu.SetResetCodeID(r.ID)
}

// AddUserDeviceIDs adds the "user_devices" edge to the UserDevice entity by IDs.
func (uu *UserUpdate) AddUserDeviceIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUserDeviceIDs(ids...)
	return uu
}

// AddUserDevices adds the "user_devices" edges to the UserDevice entity.
func (uu *UserUpdate) AddUserDevices(u ...*UserDevice) *UserUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.AddUserDeviceIDs(ids...)
}

// AddUserActionIDs adds the "user_actions" edge to the UserAction entity by IDs.
func (uu *UserUpdate) AddUserActionIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUserActionIDs(ids...)
	return uu
}

// AddUserActions adds the "user_actions" edges to the UserAction entity.
func (uu *UserUpdate) AddUserActions(u ...*UserAction) *UserUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.AddUserActionIDs(ids...)
}

// AddUserRoleIDs adds the "user_roles" edge to the UserRole entity by IDs.
func (uu *UserUpdate) AddUserRoleIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUserRoleIDs(ids...)
	return uu
}

// AddUserRoles adds the "user_roles" edges to the UserRole entity.
func (uu *UserUpdate) AddUserRoles(u ...*UserRole) *UserUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.AddUserRoleIDs(ids...)
}

// AddBlacklistedTokenIDs adds the "blacklisted_tokens" edge to the BlacklistedToken entity by IDs.
func (uu *UserUpdate) AddBlacklistedTokenIDs(ids ...int) *UserUpdate {
	uu.mutation.AddBlacklistedTokenIDs(ids...)
	return uu
}

// AddBlacklistedTokens adds the "blacklisted_tokens" edges to the BlacklistedToken entity.
func (uu *UserUpdate) AddBlacklistedTokens(b ...*BlacklistedToken) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.AddBlacklistedTokenIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearUserDetails clears the "user_details" edge to the UserDetails entity.
func (uu *UserUpdate) ClearUserDetails() *UserUpdate {
	uu.mutation.ClearUserDetails()
	return uu
}

// ClearUserSettings clears the "user_settings" edge to the UserSettings entity.
func (uu *UserUpdate) ClearUserSettings() *UserUpdate {
	uu.mutation.ClearUserSettings()
	return uu
}

// ClearActivationCode clears the "activation_code" edge to the ActivationCode entity.
func (uu *UserUpdate) ClearActivationCode() *UserUpdate {
	uu.mutation.ClearActivationCode()
	return uu
}

// ClearVerificationCode clears the "verification_code" edge to the VerificationCode entity.
func (uu *UserUpdate) ClearVerificationCode() *UserUpdate {
	uu.mutation.ClearVerificationCode()
	return uu
}

// ClearSecondFactorCode clears the "second_factor_code" edge to the SecondFactorCode entity.
func (uu *UserUpdate) ClearSecondFactorCode() *UserUpdate {
	uu.mutation.ClearSecondFactorCode()
	return uu
}

// ClearResetCode clears the "reset_code" edge to the ResetCode entity.
func (uu *UserUpdate) ClearResetCode() *UserUpdate {
	uu.mutation.ClearResetCode()
	return uu
}

// ClearUserDevices clears all "user_devices" edges to the UserDevice entity.
func (uu *UserUpdate) ClearUserDevices() *UserUpdate {
	uu.mutation.ClearUserDevices()
	return uu
}

// RemoveUserDeviceIDs removes the "user_devices" edge to UserDevice entities by IDs.
func (uu *UserUpdate) RemoveUserDeviceIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUserDeviceIDs(ids...)
	return uu
}

// RemoveUserDevices removes "user_devices" edges to UserDevice entities.
func (uu *UserUpdate) RemoveUserDevices(u ...*UserDevice) *UserUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.RemoveUserDeviceIDs(ids...)
}

// ClearUserActions clears all "user_actions" edges to the UserAction entity.
func (uu *UserUpdate) ClearUserActions() *UserUpdate {
	uu.mutation.ClearUserActions()
	return uu
}

// RemoveUserActionIDs removes the "user_actions" edge to UserAction entities by IDs.
func (uu *UserUpdate) RemoveUserActionIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUserActionIDs(ids...)
	return uu
}

// RemoveUserActions removes "user_actions" edges to UserAction entities.
func (uu *UserUpdate) RemoveUserActions(u ...*UserAction) *UserUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.RemoveUserActionIDs(ids...)
}

// ClearUserRoles clears all "user_roles" edges to the UserRole entity.
func (uu *UserUpdate) ClearUserRoles() *UserUpdate {
	uu.mutation.ClearUserRoles()
	return uu
}

// RemoveUserRoleIDs removes the "user_roles" edge to UserRole entities by IDs.
func (uu *UserUpdate) RemoveUserRoleIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUserRoleIDs(ids...)
	return uu
}

// RemoveUserRoles removes "user_roles" edges to UserRole entities.
func (uu *UserUpdate) RemoveUserRoles(u ...*UserRole) *UserUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uu.RemoveUserRoleIDs(ids...)
}

// ClearBlacklistedTokens clears all "blacklisted_tokens" edges to the BlacklistedToken entity.
func (uu *UserUpdate) ClearBlacklistedTokens() *UserUpdate {
	uu.mutation.ClearBlacklistedTokens()
	return uu
}

// RemoveBlacklistedTokenIDs removes the "blacklisted_tokens" edge to BlacklistedToken entities by IDs.
func (uu *UserUpdate) RemoveBlacklistedTokenIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveBlacklistedTokenIDs(ids...)
	return uu
}

// RemoveBlacklistedTokens removes "blacklisted_tokens" edges to BlacklistedToken entities.
func (uu *UserUpdate) RemoveBlacklistedTokens(b ...*BlacklistedToken) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.RemoveBlacklistedTokenIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *UserUpdate) check() error {
	if v, ok := uu.mutation.Mail(); ok {
		if err := user.MailValidator(v); err != nil {
			return &ValidationError{Name: "mail", err: fmt.Errorf(`ent: validator failed for field "User.mail": %w`, err)}
		}
	}
	if v, ok := uu.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	return nil
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Mail(); ok {
		_spec.SetField(user.FieldMail, field.TypeString, value)
	}
	if value, ok := uu.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if uu.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := uu.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := uu.mutation.Active(); ok {
		_spec.SetField(user.FieldActive, field.TypeBool, value)
	}
	if value, ok := uu.mutation.Verified(); ok {
		_spec.SetField(user.FieldVerified, field.TypeBool, value)
	}
	if value, ok := uu.mutation.Blacklisted(); ok {
		_spec.SetField(user.FieldBlacklisted, field.TypeBool, value)
	}
	if value, ok := uu.mutation.Removed(); ok {
		_spec.SetField(user.FieldRemoved, field.TypeBool, value)
	}
	if value, ok := uu.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uu.mutation.SubscriptionIds(); ok {
		_spec.SetField(user.FieldSubscriptionIds, field.TypeJSON, value)
	}
	if value, ok := uu.mutation.AppendedSubscriptionIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldSubscriptionIds, value)
		})
	}
	if value, ok := uu.mutation.TeamIds(); ok {
		_spec.SetField(user.FieldTeamIds, field.TypeJSON, value)
	}
	if value, ok := uu.mutation.AppendedTeamIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldTeamIds, value)
		})
	}
	if value, ok := uu.mutation.OrganizationIds(); ok {
		_spec.SetField(user.FieldOrganizationIds, field.TypeJSON, value)
	}
	if value, ok := uu.mutation.AppendedOrganizationIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldOrganizationIds, value)
		})
	}
	if uu.mutation.UserDetailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.UserDetailsTable,
			Columns: []string{user.UserDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdetails.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserDetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.UserDetailsTable,
			Columns: []string{user.UserDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdetails.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserSettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.UserSettingsTable,
			Columns: []string{user.UserSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersettings.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserSettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.UserSettingsTable,
			Columns: []string{user.UserSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.ActivationCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ActivationCodeTable,
			Columns: []string{user.ActivationCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activationcode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.ActivationCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ActivationCodeTable,
			Columns: []string{user.ActivationCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activationcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.VerificationCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.VerificationCodeTable,
			Columns: []string{user.VerificationCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationcode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.VerificationCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.VerificationCodeTable,
			Columns: []string{user.VerificationCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.SecondFactorCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SecondFactorCodeTable,
			Columns: []string{user.SecondFactorCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secondfactorcode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.SecondFactorCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SecondFactorCodeTable,
			Columns: []string{user.SecondFactorCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secondfactorcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.ResetCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ResetCodeTable,
			Columns: []string{user.ResetCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resetcode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.ResetCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ResetCodeTable,
			Columns: []string{user.ResetCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resetcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserDevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDevicesTable,
			Columns: []string{user.UserDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserDevicesIDs(); len(nodes) > 0 && !uu.mutation.UserDevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDevicesTable,
			Columns: []string{user.UserDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserDevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDevicesTable,
			Columns: []string{user.UserDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserActionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserActionsTable,
			Columns: user.UserActionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserActionsIDs(); len(nodes) > 0 && !uu.mutation.UserActionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserActionsTable,
			Columns: user.UserActionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserActionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserActionsTable,
			Columns: user.UserActionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserRolesTable,
			Columns: user.UserRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedUserRolesIDs(); len(nodes) > 0 && !uu.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserRolesTable,
			Columns: user.UserRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserRolesTable,
			Columns: user.UserRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.BlacklistedTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.BlacklistedTokensTable,
			Columns: []string{user.BlacklistedTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blacklistedtoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedBlacklistedTokensIDs(); len(nodes) > 0 && !uu.mutation.BlacklistedTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.BlacklistedTokensTable,
			Columns: []string{user.BlacklistedTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blacklistedtoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.BlacklistedTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.BlacklistedTokensTable,
			Columns: []string{user.BlacklistedTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blacklistedtoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetMail sets the "mail" field.
func (uuo *UserUpdateOne) SetMail(s string) *UserUpdateOne {
	uuo.mutation.SetMail(s)
	return uuo
}

// SetNillableMail sets the "mail" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableMail(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetMail(*s)
	}
	return uuo
}

// SetPhone sets the "phone" field.
func (uuo *UserUpdateOne) SetPhone(s string) *UserUpdateOne {
	uuo.mutation.SetPhone(s)
	return uuo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePhone(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetPhone(*s)
	}
	return uuo
}

// ClearPhone clears the value of the "phone" field.
func (uuo *UserUpdateOne) ClearPhone() *UserUpdateOne {
	uuo.mutation.ClearPhone()
	return uuo
}

// SetPassword sets the "password" field.
func (uuo *UserUpdateOne) SetPassword(s string) *UserUpdateOne {
	uuo.mutation.SetPassword(s)
	return uuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePassword(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetPassword(*s)
	}
	return uuo
}

// SetActive sets the "active" field.
func (uuo *UserUpdateOne) SetActive(b bool) *UserUpdateOne {
	uuo.mutation.SetActive(b)
	return uuo
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableActive(b *bool) *UserUpdateOne {
	if b != nil {
		uuo.SetActive(*b)
	}
	return uuo
}

// SetVerified sets the "verified" field.
func (uuo *UserUpdateOne) SetVerified(b bool) *UserUpdateOne {
	uuo.mutation.SetVerified(b)
	return uuo
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableVerified(b *bool) *UserUpdateOne {
	if b != nil {
		uuo.SetVerified(*b)
	}
	return uuo
}

// SetBlacklisted sets the "blacklisted" field.
func (uuo *UserUpdateOne) SetBlacklisted(b bool) *UserUpdateOne {
	uuo.mutation.SetBlacklisted(b)
	return uuo
}

// SetNillableBlacklisted sets the "blacklisted" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableBlacklisted(b *bool) *UserUpdateOne {
	if b != nil {
		uuo.SetBlacklisted(*b)
	}
	return uuo
}

// SetRemoved sets the "removed" field.
func (uuo *UserUpdateOne) SetRemoved(b bool) *UserUpdateOne {
	uuo.mutation.SetRemoved(b)
	return uuo
}

// SetNillableRemoved sets the "removed" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableRemoved(b *bool) *UserUpdateOne {
	if b != nil {
		uuo.SetRemoved(*b)
	}
	return uuo
}

// SetUpdatedAt sets the "updated_at" field.
func (uuo *UserUpdateOne) SetUpdatedAt(t time.Time) *UserUpdateOne {
	uuo.mutation.SetUpdatedAt(t)
	return uuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUpdatedAt(t *time.Time) *UserUpdateOne {
	if t != nil {
		uuo.SetUpdatedAt(*t)
	}
	return uuo
}

// SetSubscriptionIds sets the "subscription_ids" field.
func (uuo *UserUpdateOne) SetSubscriptionIds(i []int) *UserUpdateOne {
	uuo.mutation.SetSubscriptionIds(i)
	return uuo
}

// AppendSubscriptionIds appends i to the "subscription_ids" field.
func (uuo *UserUpdateOne) AppendSubscriptionIds(i []int) *UserUpdateOne {
	uuo.mutation.AppendSubscriptionIds(i)
	return uuo
}

// SetTeamIds sets the "team_ids" field.
func (uuo *UserUpdateOne) SetTeamIds(i []int) *UserUpdateOne {
	uuo.mutation.SetTeamIds(i)
	return uuo
}

// AppendTeamIds appends i to the "team_ids" field.
func (uuo *UserUpdateOne) AppendTeamIds(i []int) *UserUpdateOne {
	uuo.mutation.AppendTeamIds(i)
	return uuo
}

// SetOrganizationIds sets the "organization_ids" field.
func (uuo *UserUpdateOne) SetOrganizationIds(i []int) *UserUpdateOne {
	uuo.mutation.SetOrganizationIds(i)
	return uuo
}

// AppendOrganizationIds appends i to the "organization_ids" field.
func (uuo *UserUpdateOne) AppendOrganizationIds(i []int) *UserUpdateOne {
	uuo.mutation.AppendOrganizationIds(i)
	return uuo
}

// SetUserDetailsID sets the "user_details" edge to the UserDetails entity by ID.
func (uuo *UserUpdateOne) SetUserDetailsID(id int) *UserUpdateOne {
	uuo.mutation.SetUserDetailsID(id)
	return uuo
}

// SetNillableUserDetailsID sets the "user_details" edge to the UserDetails entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUserDetailsID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetUserDetailsID(*id)
	}
	return uuo
}

// SetUserDetails sets the "user_details" edge to the UserDetails entity.
func (uuo *UserUpdateOne) SetUserDetails(u *UserDetails) *UserUpdateOne {
	return uuo.SetUserDetailsID(u.ID)
}

// SetUserSettingsID sets the "user_settings" edge to the UserSettings entity by ID.
func (uuo *UserUpdateOne) SetUserSettingsID(id int) *UserUpdateOne {
	uuo.mutation.SetUserSettingsID(id)
	return uuo
}

// SetNillableUserSettingsID sets the "user_settings" edge to the UserSettings entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUserSettingsID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetUserSettingsID(*id)
	}
	return uuo
}

// SetUserSettings sets the "user_settings" edge to the UserSettings entity.
func (uuo *UserUpdateOne) SetUserSettings(u *UserSettings) *UserUpdateOne {
	return uuo.SetUserSettingsID(u.ID)
}

// SetActivationCodeID sets the "activation_code" edge to the ActivationCode entity by ID.
func (uuo *UserUpdateOne) SetActivationCodeID(id int) *UserUpdateOne {
	uuo.mutation.SetActivationCodeID(id)
	return uuo
}

// SetNillableActivationCodeID sets the "activation_code" edge to the ActivationCode entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableActivationCodeID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetActivationCodeID(*id)
	}
	return uuo
}

// SetActivationCode sets the "activation_code" edge to the ActivationCode entity.
func (uuo *UserUpdateOne) SetActivationCode(a *ActivationCode) *UserUpdateOne {
	return uuo.SetActivationCodeID(a.ID)
}

// SetVerificationCodeID sets the "verification_code" edge to the VerificationCode entity by ID.
func (uuo *UserUpdateOne) SetVerificationCodeID(id int) *UserUpdateOne {
	uuo.mutation.SetVerificationCodeID(id)
	return uuo
}

// SetNillableVerificationCodeID sets the "verification_code" edge to the VerificationCode entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableVerificationCodeID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetVerificationCodeID(*id)
	}
	return uuo
}

// SetVerificationCode sets the "verification_code" edge to the VerificationCode entity.
func (uuo *UserUpdateOne) SetVerificationCode(v *VerificationCode) *UserUpdateOne {
	return uuo.SetVerificationCodeID(v.ID)
}

// SetSecondFactorCodeID sets the "second_factor_code" edge to the SecondFactorCode entity by ID.
func (uuo *UserUpdateOne) SetSecondFactorCodeID(id int) *UserUpdateOne {
	uuo.mutation.SetSecondFactorCodeID(id)
	return uuo
}

// SetNillableSecondFactorCodeID sets the "second_factor_code" edge to the SecondFactorCode entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableSecondFactorCodeID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetSecondFactorCodeID(*id)
	}
	return uuo
}

// SetSecondFactorCode sets the "second_factor_code" edge to the SecondFactorCode entity.
func (uuo *UserUpdateOne) SetSecondFactorCode(s *SecondFactorCode) *UserUpdateOne {
	return uuo.SetSecondFactorCodeID(s.ID)
}

// SetResetCodeID sets the "reset_code" edge to the ResetCode entity by ID.
func (uuo *UserUpdateOne) SetResetCodeID(id int) *UserUpdateOne {
	uuo.mutation.SetResetCodeID(id)
	return uuo
}

// SetNillableResetCodeID sets the "reset_code" edge to the ResetCode entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableResetCodeID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetResetCodeID(*id)
	}
	return uuo
}

// SetResetCode sets the "reset_code" edge to the ResetCode entity.
func (uuo *UserUpdateOne) SetResetCode(r *ResetCode) *UserUpdateOne {
	return uuo.SetResetCodeID(r.ID)
}

// AddUserDeviceIDs adds the "user_devices" edge to the UserDevice entity by IDs.
func (uuo *UserUpdateOne) AddUserDeviceIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUserDeviceIDs(ids...)
	return uuo
}

// AddUserDevices adds the "user_devices" edges to the UserDevice entity.
func (uuo *UserUpdateOne) AddUserDevices(u ...*UserDevice) *UserUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.AddUserDeviceIDs(ids...)
}

// AddUserActionIDs adds the "user_actions" edge to the UserAction entity by IDs.
func (uuo *UserUpdateOne) AddUserActionIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUserActionIDs(ids...)
	return uuo
}

// AddUserActions adds the "user_actions" edges to the UserAction entity.
func (uuo *UserUpdateOne) AddUserActions(u ...*UserAction) *UserUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.AddUserActionIDs(ids...)
}

// AddUserRoleIDs adds the "user_roles" edge to the UserRole entity by IDs.
func (uuo *UserUpdateOne) AddUserRoleIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUserRoleIDs(ids...)
	return uuo
}

// AddUserRoles adds the "user_roles" edges to the UserRole entity.
func (uuo *UserUpdateOne) AddUserRoles(u ...*UserRole) *UserUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.AddUserRoleIDs(ids...)
}

// AddBlacklistedTokenIDs adds the "blacklisted_tokens" edge to the BlacklistedToken entity by IDs.
func (uuo *UserUpdateOne) AddBlacklistedTokenIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddBlacklistedTokenIDs(ids...)
	return uuo
}

// AddBlacklistedTokens adds the "blacklisted_tokens" edges to the BlacklistedToken entity.
func (uuo *UserUpdateOne) AddBlacklistedTokens(b ...*BlacklistedToken) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.AddBlacklistedTokenIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearUserDetails clears the "user_details" edge to the UserDetails entity.
func (uuo *UserUpdateOne) ClearUserDetails() *UserUpdateOne {
	uuo.mutation.ClearUserDetails()
	return uuo
}

// ClearUserSettings clears the "user_settings" edge to the UserSettings entity.
func (uuo *UserUpdateOne) ClearUserSettings() *UserUpdateOne {
	uuo.mutation.ClearUserSettings()
	return uuo
}

// ClearActivationCode clears the "activation_code" edge to the ActivationCode entity.
func (uuo *UserUpdateOne) ClearActivationCode() *UserUpdateOne {
	uuo.mutation.ClearActivationCode()
	return uuo
}

// ClearVerificationCode clears the "verification_code" edge to the VerificationCode entity.
func (uuo *UserUpdateOne) ClearVerificationCode() *UserUpdateOne {
	uuo.mutation.ClearVerificationCode()
	return uuo
}

// ClearSecondFactorCode clears the "second_factor_code" edge to the SecondFactorCode entity.
func (uuo *UserUpdateOne) ClearSecondFactorCode() *UserUpdateOne {
	uuo.mutation.ClearSecondFactorCode()
	return uuo
}

// ClearResetCode clears the "reset_code" edge to the ResetCode entity.
func (uuo *UserUpdateOne) ClearResetCode() *UserUpdateOne {
	uuo.mutation.ClearResetCode()
	return uuo
}

// ClearUserDevices clears all "user_devices" edges to the UserDevice entity.
func (uuo *UserUpdateOne) ClearUserDevices() *UserUpdateOne {
	uuo.mutation.ClearUserDevices()
	return uuo
}

// RemoveUserDeviceIDs removes the "user_devices" edge to UserDevice entities by IDs.
func (uuo *UserUpdateOne) RemoveUserDeviceIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUserDeviceIDs(ids...)
	return uuo
}

// RemoveUserDevices removes "user_devices" edges to UserDevice entities.
func (uuo *UserUpdateOne) RemoveUserDevices(u ...*UserDevice) *UserUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.RemoveUserDeviceIDs(ids...)
}

// ClearUserActions clears all "user_actions" edges to the UserAction entity.
func (uuo *UserUpdateOne) ClearUserActions() *UserUpdateOne {
	uuo.mutation.ClearUserActions()
	return uuo
}

// RemoveUserActionIDs removes the "user_actions" edge to UserAction entities by IDs.
func (uuo *UserUpdateOne) RemoveUserActionIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUserActionIDs(ids...)
	return uuo
}

// RemoveUserActions removes "user_actions" edges to UserAction entities.
func (uuo *UserUpdateOne) RemoveUserActions(u ...*UserAction) *UserUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.RemoveUserActionIDs(ids...)
}

// ClearUserRoles clears all "user_roles" edges to the UserRole entity.
func (uuo *UserUpdateOne) ClearUserRoles() *UserUpdateOne {
	uuo.mutation.ClearUserRoles()
	return uuo
}

// RemoveUserRoleIDs removes the "user_roles" edge to UserRole entities by IDs.
func (uuo *UserUpdateOne) RemoveUserRoleIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUserRoleIDs(ids...)
	return uuo
}

// RemoveUserRoles removes "user_roles" edges to UserRole entities.
func (uuo *UserUpdateOne) RemoveUserRoles(u ...*UserRole) *UserUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uuo.RemoveUserRoleIDs(ids...)
}

// ClearBlacklistedTokens clears all "blacklisted_tokens" edges to the BlacklistedToken entity.
func (uuo *UserUpdateOne) ClearBlacklistedTokens() *UserUpdateOne {
	uuo.mutation.ClearBlacklistedTokens()
	return uuo
}

// RemoveBlacklistedTokenIDs removes the "blacklisted_tokens" edge to BlacklistedToken entities by IDs.
func (uuo *UserUpdateOne) RemoveBlacklistedTokenIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveBlacklistedTokenIDs(ids...)
	return uuo
}

// RemoveBlacklistedTokens removes "blacklisted_tokens" edges to BlacklistedToken entities.
func (uuo *UserUpdateOne) RemoveBlacklistedTokens(b ...*BlacklistedToken) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.RemoveBlacklistedTokenIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *UserUpdateOne) check() error {
	if v, ok := uuo.mutation.Mail(); ok {
		if err := user.MailValidator(v); err != nil {
			return &ValidationError{Name: "mail", err: fmt.Errorf(`ent: validator failed for field "User.mail": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	return nil
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := uuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Mail(); ok {
		_spec.SetField(user.FieldMail, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if uuo.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := uuo.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Active(); ok {
		_spec.SetField(user.FieldActive, field.TypeBool, value)
	}
	if value, ok := uuo.mutation.Verified(); ok {
		_spec.SetField(user.FieldVerified, field.TypeBool, value)
	}
	if value, ok := uuo.mutation.Blacklisted(); ok {
		_spec.SetField(user.FieldBlacklisted, field.TypeBool, value)
	}
	if value, ok := uuo.mutation.Removed(); ok {
		_spec.SetField(user.FieldRemoved, field.TypeBool, value)
	}
	if value, ok := uuo.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uuo.mutation.SubscriptionIds(); ok {
		_spec.SetField(user.FieldSubscriptionIds, field.TypeJSON, value)
	}
	if value, ok := uuo.mutation.AppendedSubscriptionIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldSubscriptionIds, value)
		})
	}
	if value, ok := uuo.mutation.TeamIds(); ok {
		_spec.SetField(user.FieldTeamIds, field.TypeJSON, value)
	}
	if value, ok := uuo.mutation.AppendedTeamIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldTeamIds, value)
		})
	}
	if value, ok := uuo.mutation.OrganizationIds(); ok {
		_spec.SetField(user.FieldOrganizationIds, field.TypeJSON, value)
	}
	if value, ok := uuo.mutation.AppendedOrganizationIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldOrganizationIds, value)
		})
	}
	if uuo.mutation.UserDetailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.UserDetailsTable,
			Columns: []string{user.UserDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdetails.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserDetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.UserDetailsTable,
			Columns: []string{user.UserDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdetails.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserSettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.UserSettingsTable,
			Columns: []string{user.UserSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersettings.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserSettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.UserSettingsTable,
			Columns: []string{user.UserSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.ActivationCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ActivationCodeTable,
			Columns: []string{user.ActivationCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activationcode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.ActivationCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ActivationCodeTable,
			Columns: []string{user.ActivationCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activationcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.VerificationCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.VerificationCodeTable,
			Columns: []string{user.VerificationCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationcode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.VerificationCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.VerificationCodeTable,
			Columns: []string{user.VerificationCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.SecondFactorCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SecondFactorCodeTable,
			Columns: []string{user.SecondFactorCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secondfactorcode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.SecondFactorCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SecondFactorCodeTable,
			Columns: []string{user.SecondFactorCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secondfactorcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.ResetCodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ResetCodeTable,
			Columns: []string{user.ResetCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resetcode.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.ResetCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ResetCodeTable,
			Columns: []string{user.ResetCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resetcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserDevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDevicesTable,
			Columns: []string{user.UserDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserDevicesIDs(); len(nodes) > 0 && !uuo.mutation.UserDevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDevicesTable,
			Columns: []string{user.UserDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserDevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDevicesTable,
			Columns: []string{user.UserDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserActionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserActionsTable,
			Columns: user.UserActionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserActionsIDs(); len(nodes) > 0 && !uuo.mutation.UserActionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserActionsTable,
			Columns: user.UserActionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserActionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserActionsTable,
			Columns: user.UserActionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserRolesTable,
			Columns: user.UserRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedUserRolesIDs(); len(nodes) > 0 && !uuo.mutation.UserRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserRolesTable,
			Columns: user.UserRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserRolesTable,
			Columns: user.UserRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.BlacklistedTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.BlacklistedTokensTable,
			Columns: []string{user.BlacklistedTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blacklistedtoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedBlacklistedTokensIDs(); len(nodes) > 0 && !uuo.mutation.BlacklistedTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.BlacklistedTokensTable,
			Columns: []string{user.BlacklistedTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blacklistedtoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.BlacklistedTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.BlacklistedTokensTable,
			Columns: []string{user.BlacklistedTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blacklistedtoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
