// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"users-service/app/models/ent/user"
	"users-service/app/models/ent/userdevice"
	"users-service/app/models/ent/usersettings"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSettingsCreate is the builder for creating a UserSettings entity.
type UserSettingsCreate struct {
	config
	mutation *UserSettingsMutation
	hooks    []Hook
}

// SetUUID sets the "UUID" field.
func (usc *UserSettingsCreate) SetUUID(s string) *UserSettingsCreate {
	usc.mutation.SetUUID(s)
	return usc
}

// SetTwoFactor sets the "two_factor" field.
func (usc *UserSettingsCreate) SetTwoFactor(b bool) *UserSettingsCreate {
	usc.mutation.SetTwoFactor(b)
	return usc
}

// SetNillableTwoFactor sets the "two_factor" field if the given value is not nil.
func (usc *UserSettingsCreate) SetNillableTwoFactor(b *bool) *UserSettingsCreate {
	if b != nil {
		usc.SetTwoFactor(*b)
	}
	return usc
}

// SetNightMode sets the "night_mode" field.
func (usc *UserSettingsCreate) SetNightMode(b bool) *UserSettingsCreate {
	usc.mutation.SetNightMode(b)
	return usc
}

// SetNillableNightMode sets the "night_mode" field if the given value is not nil.
func (usc *UserSettingsCreate) SetNillableNightMode(b *bool) *UserSettingsCreate {
	if b != nil {
		usc.SetNightMode(*b)
	}
	return usc
}

// SetCreatedAt sets the "created_at" field.
func (usc *UserSettingsCreate) SetCreatedAt(t time.Time) *UserSettingsCreate {
	usc.mutation.SetCreatedAt(t)
	return usc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (usc *UserSettingsCreate) SetNillableCreatedAt(t *time.Time) *UserSettingsCreate {
	if t != nil {
		usc.SetCreatedAt(*t)
	}
	return usc
}

// SetUpdatedAt sets the "updated_at" field.
func (usc *UserSettingsCreate) SetUpdatedAt(t time.Time) *UserSettingsCreate {
	usc.mutation.SetUpdatedAt(t)
	return usc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (usc *UserSettingsCreate) SetNillableUpdatedAt(t *time.Time) *UserSettingsCreate {
	if t != nil {
		usc.SetUpdatedAt(*t)
	}
	return usc
}

// SetID sets the "id" field.
func (usc *UserSettingsCreate) SetID(i int) *UserSettingsCreate {
	usc.mutation.SetID(i)
	return usc
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (usc *UserSettingsCreate) SetOwnerID(id int) *UserSettingsCreate {
	usc.mutation.SetOwnerID(id)
	return usc
}

// SetOwner sets the "owner" edge to the User entity.
func (usc *UserSettingsCreate) SetOwner(u *User) *UserSettingsCreate {
	return usc.SetOwnerID(u.ID)
}

// SetSecondFactorTargetID sets the "second_factor_target" edge to the UserDevice entity by ID.
func (usc *UserSettingsCreate) SetSecondFactorTargetID(id int) *UserSettingsCreate {
	usc.mutation.SetSecondFactorTargetID(id)
	return usc
}

// SetNillableSecondFactorTargetID sets the "second_factor_target" edge to the UserDevice entity by ID if the given value is not nil.
func (usc *UserSettingsCreate) SetNillableSecondFactorTargetID(id *int) *UserSettingsCreate {
	if id != nil {
		usc = usc.SetSecondFactorTargetID(*id)
	}
	return usc
}

// SetSecondFactorTarget sets the "second_factor_target" edge to the UserDevice entity.
func (usc *UserSettingsCreate) SetSecondFactorTarget(u *UserDevice) *UserSettingsCreate {
	return usc.SetSecondFactorTargetID(u.ID)
}

// AddNotificationTargetDeviceIDs adds the "notification_target_devices" edge to the UserDevice entity by IDs.
func (usc *UserSettingsCreate) AddNotificationTargetDeviceIDs(ids ...int) *UserSettingsCreate {
	usc.mutation.AddNotificationTargetDeviceIDs(ids...)
	return usc
}

// AddNotificationTargetDevices adds the "notification_target_devices" edges to the UserDevice entity.
func (usc *UserSettingsCreate) AddNotificationTargetDevices(u ...*UserDevice) *UserSettingsCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return usc.AddNotificationTargetDeviceIDs(ids...)
}

// Mutation returns the UserSettingsMutation object of the builder.
func (usc *UserSettingsCreate) Mutation() *UserSettingsMutation {
	return usc.mutation
}

// Save creates the UserSettings in the database.
func (usc *UserSettingsCreate) Save(ctx context.Context) (*UserSettings, error) {
	usc.defaults()
	return withHooks(ctx, usc.sqlSave, usc.mutation, usc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (usc *UserSettingsCreate) SaveX(ctx context.Context) *UserSettings {
	v, err := usc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (usc *UserSettingsCreate) Exec(ctx context.Context) error {
	_, err := usc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usc *UserSettingsCreate) ExecX(ctx context.Context) {
	if err := usc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (usc *UserSettingsCreate) defaults() {
	if _, ok := usc.mutation.TwoFactor(); !ok {
		v := usersettings.DefaultTwoFactor
		usc.mutation.SetTwoFactor(v)
	}
	if _, ok := usc.mutation.NightMode(); !ok {
		v := usersettings.DefaultNightMode
		usc.mutation.SetNightMode(v)
	}
	if _, ok := usc.mutation.CreatedAt(); !ok {
		v := usersettings.DefaultCreatedAt()
		usc.mutation.SetCreatedAt(v)
	}
	if _, ok := usc.mutation.UpdatedAt(); !ok {
		v := usersettings.DefaultUpdatedAt()
		usc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (usc *UserSettingsCreate) check() error {
	if _, ok := usc.mutation.UUID(); !ok {
		return &ValidationError{Name: "UUID", err: errors.New(`ent: missing required field "UserSettings.UUID"`)}
	}
	if _, ok := usc.mutation.TwoFactor(); !ok {
		return &ValidationError{Name: "two_factor", err: errors.New(`ent: missing required field "UserSettings.two_factor"`)}
	}
	if _, ok := usc.mutation.NightMode(); !ok {
		return &ValidationError{Name: "night_mode", err: errors.New(`ent: missing required field "UserSettings.night_mode"`)}
	}
	if _, ok := usc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserSettings.created_at"`)}
	}
	if _, ok := usc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserSettings.updated_at"`)}
	}
	if len(usc.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "UserSettings.owner"`)}
	}
	return nil
}

func (usc *UserSettingsCreate) sqlSave(ctx context.Context) (*UserSettings, error) {
	if err := usc.check(); err != nil {
		return nil, err
	}
	_node, _spec := usc.createSpec()
	if err := sqlgraph.CreateNode(ctx, usc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	usc.mutation.id = &_node.ID
	usc.mutation.done = true
	return _node, nil
}

func (usc *UserSettingsCreate) createSpec() (*UserSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSettings{config: usc.config}
		_spec = sqlgraph.NewCreateSpec(usersettings.Table, sqlgraph.NewFieldSpec(usersettings.FieldID, field.TypeInt))
	)
	if id, ok := usc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := usc.mutation.UUID(); ok {
		_spec.SetField(usersettings.FieldUUID, field.TypeString, value)
		_node.UUID = value
	}
	if value, ok := usc.mutation.TwoFactor(); ok {
		_spec.SetField(usersettings.FieldTwoFactor, field.TypeBool, value)
		_node.TwoFactor = value
	}
	if value, ok := usc.mutation.NightMode(); ok {
		_spec.SetField(usersettings.FieldNightMode, field.TypeBool, value)
		_node.NightMode = value
	}
	if value, ok := usc.mutation.CreatedAt(); ok {
		_spec.SetField(usersettings.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := usc.mutation.UpdatedAt(); ok {
		_spec.SetField(usersettings.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := usc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usersettings.OwnerTable,
			Columns: []string{usersettings.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_user_settings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := usc.mutation.SecondFactorTargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   usersettings.SecondFactorTargetTable,
			Columns: []string{usersettings.SecondFactorTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := usc.mutation.NotificationTargetDevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersettings.NotificationTargetDevicesTable,
			Columns: []string{usersettings.NotificationTargetDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserSettingsCreateBulk is the builder for creating many UserSettings entities in bulk.
type UserSettingsCreateBulk struct {
	config
	err      error
	builders []*UserSettingsCreate
}

// Save creates the UserSettings entities in the database.
func (uscb *UserSettingsCreateBulk) Save(ctx context.Context) ([]*UserSettings, error) {
	if uscb.err != nil {
		return nil, uscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uscb.builders))
	nodes := make([]*UserSettings, len(uscb.builders))
	mutators := make([]Mutator, len(uscb.builders))
	for i := range uscb.builders {
		func(i int, root context.Context) {
			builder := uscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uscb *UserSettingsCreateBulk) SaveX(ctx context.Context) []*UserSettings {
	v, err := uscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uscb *UserSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := uscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uscb *UserSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := uscb.Exec(ctx); err != nil {
		panic(err)
	}
}
