// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"users-service/app/models/ent/useraction"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserAction is the model entity for the UserAction schema.
type UserAction struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id"`
	// Type holds the value of the "type" field.
	Type string `json:"type"`
	// Action holds the value of the "action" field.
	Action string `json:"action"`
	// Details holds the value of the "details" field.
	Details string `json:"details"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserActionQuery when eager-loading is set.
	Edges        UserActionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserActionEdges holds the relations/edges for other nodes in the graph.
type UserActionEdges struct {
	// Author holds the value of the author edge.
	Author []*User `json:"author"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AuthorOrErr returns the Author value or an error if the edge
// was not loaded in eager-loading.
func (e UserActionEdges) AuthorOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Author, nil
	}
	return nil, &NotLoadedError{edge: "author"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case useraction.FieldID:
			values[i] = new(sql.NullInt64)
		case useraction.FieldType, useraction.FieldAction, useraction.FieldDetails:
			values[i] = new(sql.NullString)
		case useraction.FieldCreatedAt, useraction.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAction fields.
func (ua *UserAction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case useraction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ua.ID = int(value.Int64)
		case useraction.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				ua.Type = value.String
			}
		case useraction.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				ua.Action = value.String
			}
		case useraction.FieldDetails:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value.Valid {
				ua.Details = value.String
			}
		case useraction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ua.CreatedAt = value.Time
			}
		case useraction.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ua.UpdatedAt = value.Time
			}
		default:
			ua.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserAction.
// This includes values selected through modifiers, order, etc.
func (ua *UserAction) Value(name string) (ent.Value, error) {
	return ua.selectValues.Get(name)
}

// QueryAuthor queries the "author" edge of the UserAction entity.
func (ua *UserAction) QueryAuthor() *UserQuery {
	return NewUserActionClient(ua.config).QueryAuthor(ua)
}

// Update returns a builder for updating this UserAction.
// Note that you need to call UserAction.Unwrap() before calling this method if this UserAction
// was returned from a transaction, and the transaction was committed or rolled back.
func (ua *UserAction) Update() *UserActionUpdateOne {
	return NewUserActionClient(ua.config).UpdateOne(ua)
}

// Unwrap unwraps the UserAction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ua *UserAction) Unwrap() *UserAction {
	_tx, ok := ua.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAction is not a transactional entity")
	}
	ua.config.driver = _tx.drv
	return ua
}

// String implements the fmt.Stringer.
func (ua *UserAction) String() string {
	var builder strings.Builder
	builder.WriteString("UserAction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ua.ID))
	builder.WriteString("type=")
	builder.WriteString(ua.Type)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(ua.Action)
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(ua.Details)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ua.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ua.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserActions is a parsable slice of UserAction.
type UserActions []*UserAction
