// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"users-service/app/models/ent/predicate"
	"users-service/app/models/ent/userdetails"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserDetailsDelete is the builder for deleting a UserDetails entity.
type UserDetailsDelete struct {
	config
	hooks    []Hook
	mutation *UserDetailsMutation
}

// Where appends a list predicates to the UserDetailsDelete builder.
func (udd *UserDetailsDelete) Where(ps ...predicate.UserDetails) *UserDetailsDelete {
	udd.mutation.Where(ps...)
	return udd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (udd *UserDetailsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, udd.sqlExec, udd.mutation, udd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (udd *UserDetailsDelete) ExecX(ctx context.Context) int {
	n, err := udd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (udd *UserDetailsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userdetails.Table, sqlgraph.NewFieldSpec(userdetails.FieldID, field.TypeInt))
	if ps := udd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, udd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	udd.mutation.done = true
	return affected, err
}

// UserDetailsDeleteOne is the builder for deleting a single UserDetails entity.
type UserDetailsDeleteOne struct {
	udd *UserDetailsDelete
}

// Where appends a list predicates to the UserDetailsDelete builder.
func (uddo *UserDetailsDeleteOne) Where(ps ...predicate.UserDetails) *UserDetailsDeleteOne {
	uddo.udd.mutation.Where(ps...)
	return uddo
}

// Exec executes the deletion query.
func (uddo *UserDetailsDeleteOne) Exec(ctx context.Context) error {
	n, err := uddo.udd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userdetails.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uddo *UserDetailsDeleteOne) ExecX(ctx context.Context) {
	if err := uddo.Exec(ctx); err != nil {
		panic(err)
	}
}
