// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"users-service/app/models/ent/activationcode"
	"users-service/app/models/ent/blacklistedtoken"
	"users-service/app/models/ent/resetcode"
	"users-service/app/models/ent/secondfactorcode"
	"users-service/app/models/ent/user"
	"users-service/app/models/ent/useraction"
	"users-service/app/models/ent/userdetails"
	"users-service/app/models/ent/userdevice"
	"users-service/app/models/ent/userrole"
	"users-service/app/models/ent/usersettings"
	"users-service/app/models/ent/verificationcode"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetMail sets the "mail" field.
func (uc *UserCreate) SetMail(s string) *UserCreate {
	uc.mutation.SetMail(s)
	return uc
}

// SetPhone sets the "phone" field.
func (uc *UserCreate) SetPhone(s string) *UserCreate {
	uc.mutation.SetPhone(s)
	return uc
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (uc *UserCreate) SetNillablePhone(s *string) *UserCreate {
	if s != nil {
		uc.SetPhone(*s)
	}
	return uc
}

// SetPassword sets the "password" field.
func (uc *UserCreate) SetPassword(s string) *UserCreate {
	uc.mutation.SetPassword(s)
	return uc
}

// SetActive sets the "active" field.
func (uc *UserCreate) SetActive(b bool) *UserCreate {
	uc.mutation.SetActive(b)
	return uc
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (uc *UserCreate) SetNillableActive(b *bool) *UserCreate {
	if b != nil {
		uc.SetActive(*b)
	}
	return uc
}

// SetVerified sets the "verified" field.
func (uc *UserCreate) SetVerified(b bool) *UserCreate {
	uc.mutation.SetVerified(b)
	return uc
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (uc *UserCreate) SetNillableVerified(b *bool) *UserCreate {
	if b != nil {
		uc.SetVerified(*b)
	}
	return uc
}

// SetBlacklisted sets the "blacklisted" field.
func (uc *UserCreate) SetBlacklisted(b bool) *UserCreate {
	uc.mutation.SetBlacklisted(b)
	return uc
}

// SetNillableBlacklisted sets the "blacklisted" field if the given value is not nil.
func (uc *UserCreate) SetNillableBlacklisted(b *bool) *UserCreate {
	if b != nil {
		uc.SetBlacklisted(*b)
	}
	return uc
}

// SetRemoved sets the "removed" field.
func (uc *UserCreate) SetRemoved(b bool) *UserCreate {
	uc.mutation.SetRemoved(b)
	return uc
}

// SetNillableRemoved sets the "removed" field if the given value is not nil.
func (uc *UserCreate) SetNillableRemoved(b *bool) *UserCreate {
	if b != nil {
		uc.SetRemoved(*b)
	}
	return uc
}

// SetCreatedAt sets the "created_at" field.
func (uc *UserCreate) SetCreatedAt(t time.Time) *UserCreate {
	uc.mutation.SetCreatedAt(t)
	return uc
}

// SetUpdatedAt sets the "updated_at" field.
func (uc *UserCreate) SetUpdatedAt(t time.Time) *UserCreate {
	uc.mutation.SetUpdatedAt(t)
	return uc
}

// SetSubscriptionIds sets the "subscription_ids" field.
func (uc *UserCreate) SetSubscriptionIds(i []int) *UserCreate {
	uc.mutation.SetSubscriptionIds(i)
	return uc
}

// SetTeamIds sets the "team_ids" field.
func (uc *UserCreate) SetTeamIds(i []int) *UserCreate {
	uc.mutation.SetTeamIds(i)
	return uc
}

// SetOrganizationIds sets the "organization_ids" field.
func (uc *UserCreate) SetOrganizationIds(i []int) *UserCreate {
	uc.mutation.SetOrganizationIds(i)
	return uc
}

// SetID sets the "id" field.
func (uc *UserCreate) SetID(i int) *UserCreate {
	uc.mutation.SetID(i)
	return uc
}

// SetUserDetailsID sets the "user_details" edge to the UserDetails entity by ID.
func (uc *UserCreate) SetUserDetailsID(id int) *UserCreate {
	uc.mutation.SetUserDetailsID(id)
	return uc
}

// SetNillableUserDetailsID sets the "user_details" edge to the UserDetails entity by ID if the given value is not nil.
func (uc *UserCreate) SetNillableUserDetailsID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetUserDetailsID(*id)
	}
	return uc
}

// SetUserDetails sets the "user_details" edge to the UserDetails entity.
func (uc *UserCreate) SetUserDetails(u *UserDetails) *UserCreate {
	return uc.SetUserDetailsID(u.ID)
}

// SetUserSettingsID sets the "user_settings" edge to the UserSettings entity by ID.
func (uc *UserCreate) SetUserSettingsID(id int) *UserCreate {
	uc.mutation.SetUserSettingsID(id)
	return uc
}

// SetNillableUserSettingsID sets the "user_settings" edge to the UserSettings entity by ID if the given value is not nil.
func (uc *UserCreate) SetNillableUserSettingsID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetUserSettingsID(*id)
	}
	return uc
}

// SetUserSettings sets the "user_settings" edge to the UserSettings entity.
func (uc *UserCreate) SetUserSettings(u *UserSettings) *UserCreate {
	return uc.SetUserSettingsID(u.ID)
}

// SetActivationCodeID sets the "activation_code" edge to the ActivationCode entity by ID.
func (uc *UserCreate) SetActivationCodeID(id int) *UserCreate {
	uc.mutation.SetActivationCodeID(id)
	return uc
}

// SetNillableActivationCodeID sets the "activation_code" edge to the ActivationCode entity by ID if the given value is not nil.
func (uc *UserCreate) SetNillableActivationCodeID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetActivationCodeID(*id)
	}
	return uc
}

// SetActivationCode sets the "activation_code" edge to the ActivationCode entity.
func (uc *UserCreate) SetActivationCode(a *ActivationCode) *UserCreate {
	return uc.SetActivationCodeID(a.ID)
}

// SetVerificationCodeID sets the "verification_code" edge to the VerificationCode entity by ID.
func (uc *UserCreate) SetVerificationCodeID(id int) *UserCreate {
	uc.mutation.SetVerificationCodeID(id)
	return uc
}

// SetNillableVerificationCodeID sets the "verification_code" edge to the VerificationCode entity by ID if the given value is not nil.
func (uc *UserCreate) SetNillableVerificationCodeID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetVerificationCodeID(*id)
	}
	return uc
}

// SetVerificationCode sets the "verification_code" edge to the VerificationCode entity.
func (uc *UserCreate) SetVerificationCode(v *VerificationCode) *UserCreate {
	return uc.SetVerificationCodeID(v.ID)
}

// SetSecondFactorCodeID sets the "second_factor_code" edge to the SecondFactorCode entity by ID.
func (uc *UserCreate) SetSecondFactorCodeID(id int) *UserCreate {
	uc.mutation.SetSecondFactorCodeID(id)
	return uc
}

// SetNillableSecondFactorCodeID sets the "second_factor_code" edge to the SecondFactorCode entity by ID if the given value is not nil.
func (uc *UserCreate) SetNillableSecondFactorCodeID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetSecondFactorCodeID(*id)
	}
	return uc
}

// SetSecondFactorCode sets the "second_factor_code" edge to the SecondFactorCode entity.
func (uc *UserCreate) SetSecondFactorCode(s *SecondFactorCode) *UserCreate {
	return uc.SetSecondFactorCodeID(s.ID)
}

// SetResetCodeID sets the "reset_code" edge to the ResetCode entity by ID.
func (uc *UserCreate) SetResetCodeID(id int) *UserCreate {
	uc.mutation.SetResetCodeID(id)
	return uc
}

// SetNillableResetCodeID sets the "reset_code" edge to the ResetCode entity by ID if the given value is not nil.
func (uc *UserCreate) SetNillableResetCodeID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetResetCodeID(*id)
	}
	return uc
}

// SetResetCode sets the "reset_code" edge to the ResetCode entity.
func (uc *UserCreate) SetResetCode(r *ResetCode) *UserCreate {
	return uc.SetResetCodeID(r.ID)
}

// AddUserDeviceIDs adds the "user_devices" edge to the UserDevice entity by IDs.
func (uc *UserCreate) AddUserDeviceIDs(ids ...int) *UserCreate {
	uc.mutation.AddUserDeviceIDs(ids...)
	return uc
}

// AddUserDevices adds the "user_devices" edges to the UserDevice entity.
func (uc *UserCreate) AddUserDevices(u ...*UserDevice) *UserCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddUserDeviceIDs(ids...)
}

// AddUserActionIDs adds the "user_actions" edge to the UserAction entity by IDs.
func (uc *UserCreate) AddUserActionIDs(ids ...int) *UserCreate {
	uc.mutation.AddUserActionIDs(ids...)
	return uc
}

// AddUserActions adds the "user_actions" edges to the UserAction entity.
func (uc *UserCreate) AddUserActions(u ...*UserAction) *UserCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddUserActionIDs(ids...)
}

// AddUserRoleIDs adds the "user_roles" edge to the UserRole entity by IDs.
func (uc *UserCreate) AddUserRoleIDs(ids ...int) *UserCreate {
	uc.mutation.AddUserRoleIDs(ids...)
	return uc
}

// AddUserRoles adds the "user_roles" edges to the UserRole entity.
func (uc *UserCreate) AddUserRoles(u ...*UserRole) *UserCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddUserRoleIDs(ids...)
}

// AddBlacklistedTokenIDs adds the "blacklisted_tokens" edge to the BlacklistedToken entity by IDs.
func (uc *UserCreate) AddBlacklistedTokenIDs(ids ...int) *UserCreate {
	uc.mutation.AddBlacklistedTokenIDs(ids...)
	return uc
}

// AddBlacklistedTokens adds the "blacklisted_tokens" edges to the BlacklistedToken entity.
func (uc *UserCreate) AddBlacklistedTokens(b ...*BlacklistedToken) *UserCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uc.AddBlacklistedTokenIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uc *UserCreate) Mutation() *UserMutation {
	return uc.mutation
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	if err := uc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, uc.sqlSave, uc.mutation, uc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uc *UserCreate) Exec(ctx context.Context) error {
	_, err := uc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uc *UserCreate) ExecX(ctx context.Context) {
	if err := uc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uc *UserCreate) defaults() error {
	if _, ok := uc.mutation.Active(); !ok {
		v := user.DefaultActive
		uc.mutation.SetActive(v)
	}
	if _, ok := uc.mutation.Verified(); !ok {
		v := user.DefaultVerified
		uc.mutation.SetVerified(v)
	}
	if _, ok := uc.mutation.Blacklisted(); !ok {
		v := user.DefaultBlacklisted
		uc.mutation.SetBlacklisted(v)
	}
	if _, ok := uc.mutation.Removed(); !ok {
		v := user.DefaultRemoved
		uc.mutation.SetRemoved(v)
	}
	if _, ok := uc.mutation.SubscriptionIds(); !ok {
		v := user.DefaultSubscriptionIds
		uc.mutation.SetSubscriptionIds(v)
	}
	if _, ok := uc.mutation.TeamIds(); !ok {
		v := user.DefaultTeamIds
		uc.mutation.SetTeamIds(v)
	}
	if _, ok := uc.mutation.OrganizationIds(); !ok {
		v := user.DefaultOrganizationIds
		uc.mutation.SetOrganizationIds(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (uc *UserCreate) check() error {
	if _, ok := uc.mutation.Mail(); !ok {
		return &ValidationError{Name: "mail", err: errors.New(`ent: missing required field "User.mail"`)}
	}
	if v, ok := uc.mutation.Mail(); ok {
		if err := user.MailValidator(v); err != nil {
			return &ValidationError{Name: "mail", err: fmt.Errorf(`ent: validator failed for field "User.mail": %w`, err)}
		}
	}
	if _, ok := uc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "User.password"`)}
	}
	if v, ok := uc.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	if _, ok := uc.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "User.active"`)}
	}
	if _, ok := uc.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`ent: missing required field "User.verified"`)}
	}
	if _, ok := uc.mutation.Blacklisted(); !ok {
		return &ValidationError{Name: "blacklisted", err: errors.New(`ent: missing required field "User.blacklisted"`)}
	}
	if _, ok := uc.mutation.Removed(); !ok {
		return &ValidationError{Name: "removed", err: errors.New(`ent: missing required field "User.removed"`)}
	}
	if _, ok := uc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := uc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	if _, ok := uc.mutation.SubscriptionIds(); !ok {
		return &ValidationError{Name: "subscription_ids", err: errors.New(`ent: missing required field "User.subscription_ids"`)}
	}
	if _, ok := uc.mutation.TeamIds(); !ok {
		return &ValidationError{Name: "team_ids", err: errors.New(`ent: missing required field "User.team_ids"`)}
	}
	if _, ok := uc.mutation.OrganizationIds(); !ok {
		return &ValidationError{Name: "organization_ids", err: errors.New(`ent: missing required field "User.organization_ids"`)}
	}
	return nil
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := uc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	uc.mutation.id = &_node.ID
	uc.mutation.done = true
	return _node, nil
}

func (uc *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: uc.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if id, ok := uc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uc.mutation.Mail(); ok {
		_spec.SetField(user.FieldMail, field.TypeString, value)
		_node.Mail = value
	}
	if value, ok := uc.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := uc.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := uc.mutation.Active(); ok {
		_spec.SetField(user.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := uc.mutation.Verified(); ok {
		_spec.SetField(user.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	if value, ok := uc.mutation.Blacklisted(); ok {
		_spec.SetField(user.FieldBlacklisted, field.TypeBool, value)
		_node.Blacklisted = value
	}
	if value, ok := uc.mutation.Removed(); ok {
		_spec.SetField(user.FieldRemoved, field.TypeBool, value)
		_node.Removed = value
	}
	if value, ok := uc.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := uc.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := uc.mutation.SubscriptionIds(); ok {
		_spec.SetField(user.FieldSubscriptionIds, field.TypeJSON, value)
		_node.SubscriptionIds = value
	}
	if value, ok := uc.mutation.TeamIds(); ok {
		_spec.SetField(user.FieldTeamIds, field.TypeJSON, value)
		_node.TeamIds = value
	}
	if value, ok := uc.mutation.OrganizationIds(); ok {
		_spec.SetField(user.FieldOrganizationIds, field.TypeJSON, value)
		_node.OrganizationIds = value
	}
	if nodes := uc.mutation.UserDetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.UserDetailsTable,
			Columns: []string{user.UserDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdetails.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.UserSettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.UserSettingsTable,
			Columns: []string{user.UserSettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersettings.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.ActivationCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ActivationCodeTable,
			Columns: []string{user.ActivationCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activationcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.VerificationCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.VerificationCodeTable,
			Columns: []string{user.VerificationCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.SecondFactorCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SecondFactorCodeTable,
			Columns: []string{user.SecondFactorCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(secondfactorcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.ResetCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.ResetCodeTable,
			Columns: []string{user.ResetCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resetcode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.UserDevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserDevicesTable,
			Columns: []string{user.UserDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.UserActionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserActionsTable,
			Columns: user.UserActionsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.UserRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UserRolesTable,
			Columns: user.UserRolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.BlacklistedTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   user.BlacklistedTokensTable,
			Columns: []string{user.BlacklistedTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(blacklistedtoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (ucb *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if ucb.err != nil {
		return nil, ucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ucb.builders))
	nodes := make([]*User, len(ucb.builders))
	mutators := make([]Mutator, len(ucb.builders))
	for i := range ucb.builders {
		func(i int, root context.Context) {
			builder := ucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucb *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := ucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucb *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := ucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucb *UserCreateBulk) ExecX(ctx context.Context) {
	if err := ucb.Exec(ctx); err != nil {
		panic(err)
	}
}
