// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"users-service/app/models/ent/predicate"
	"users-service/app/models/ent/useraction"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserActionDelete is the builder for deleting a UserAction entity.
type UserActionDelete struct {
	config
	hooks    []Hook
	mutation *UserActionMutation
}

// Where appends a list predicates to the UserActionDelete builder.
func (uad *UserActionDelete) Where(ps ...predicate.UserAction) *UserActionDelete {
	uad.mutation.Where(ps...)
	return uad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uad *UserActionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uad.sqlExec, uad.mutation, uad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uad *UserActionDelete) ExecX(ctx context.Context) int {
	n, err := uad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uad *UserActionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(useraction.Table, sqlgraph.NewFieldSpec(useraction.FieldID, field.TypeInt))
	if ps := uad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uad.mutation.done = true
	return affected, err
}

// UserActionDeleteOne is the builder for deleting a single UserAction entity.
type UserActionDeleteOne struct {
	uad *UserActionDelete
}

// Where appends a list predicates to the UserActionDelete builder.
func (uado *UserActionDeleteOne) Where(ps ...predicate.UserAction) *UserActionDeleteOne {
	uado.uad.mutation.Where(ps...)
	return uado
}

// Exec executes the deletion query.
func (uado *UserActionDeleteOne) Exec(ctx context.Context) error {
	n, err := uado.uad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useraction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uado *UserActionDeleteOne) ExecX(ctx context.Context) {
	if err := uado.Exec(ctx); err != nil {
		panic(err)
	}
}
