// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"users-service/app/models/ent/predicate"
	"users-service/app/models/ent/user"
	"users-service/app/models/ent/userdevice"
	"users-service/app/models/ent/usersettings"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSettingsUpdate is the builder for updating UserSettings entities.
type UserSettingsUpdate struct {
	config
	hooks    []Hook
	mutation *UserSettingsMutation
}

// Where appends a list predicates to the UserSettingsUpdate builder.
func (usu *UserSettingsUpdate) Where(ps ...predicate.UserSettings) *UserSettingsUpdate {
	usu.mutation.Where(ps...)
	return usu
}

// SetUUID sets the "UUID" field.
func (usu *UserSettingsUpdate) SetUUID(s string) *UserSettingsUpdate {
	usu.mutation.SetUUID(s)
	return usu
}

// SetNillableUUID sets the "UUID" field if the given value is not nil.
func (usu *UserSettingsUpdate) SetNillableUUID(s *string) *UserSettingsUpdate {
	if s != nil {
		usu.SetUUID(*s)
	}
	return usu
}

// SetTwoFactor sets the "two_factor" field.
func (usu *UserSettingsUpdate) SetTwoFactor(b bool) *UserSettingsUpdate {
	usu.mutation.SetTwoFactor(b)
	return usu
}

// SetNillableTwoFactor sets the "two_factor" field if the given value is not nil.
func (usu *UserSettingsUpdate) SetNillableTwoFactor(b *bool) *UserSettingsUpdate {
	if b != nil {
		usu.SetTwoFactor(*b)
	}
	return usu
}

// SetNightMode sets the "night_mode" field.
func (usu *UserSettingsUpdate) SetNightMode(b bool) *UserSettingsUpdate {
	usu.mutation.SetNightMode(b)
	return usu
}

// SetNillableNightMode sets the "night_mode" field if the given value is not nil.
func (usu *UserSettingsUpdate) SetNillableNightMode(b *bool) *UserSettingsUpdate {
	if b != nil {
		usu.SetNightMode(*b)
	}
	return usu
}

// SetCreatedAt sets the "created_at" field.
func (usu *UserSettingsUpdate) SetCreatedAt(t time.Time) *UserSettingsUpdate {
	usu.mutation.SetCreatedAt(t)
	return usu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (usu *UserSettingsUpdate) SetNillableCreatedAt(t *time.Time) *UserSettingsUpdate {
	if t != nil {
		usu.SetCreatedAt(*t)
	}
	return usu
}

// SetUpdatedAt sets the "updated_at" field.
func (usu *UserSettingsUpdate) SetUpdatedAt(t time.Time) *UserSettingsUpdate {
	usu.mutation.SetUpdatedAt(t)
	return usu
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (usu *UserSettingsUpdate) SetOwnerID(id int) *UserSettingsUpdate {
	usu.mutation.SetOwnerID(id)
	return usu
}

// SetOwner sets the "owner" edge to the User entity.
func (usu *UserSettingsUpdate) SetOwner(u *User) *UserSettingsUpdate {
	return usu.SetOwnerID(u.ID)
}

// SetSecondFactorTargetID sets the "second_factor_target" edge to the UserDevice entity by ID.
func (usu *UserSettingsUpdate) SetSecondFactorTargetID(id int) *UserSettingsUpdate {
	usu.mutation.SetSecondFactorTargetID(id)
	return usu
}

// SetNillableSecondFactorTargetID sets the "second_factor_target" edge to the UserDevice entity by ID if the given value is not nil.
func (usu *UserSettingsUpdate) SetNillableSecondFactorTargetID(id *int) *UserSettingsUpdate {
	if id != nil {
		usu = usu.SetSecondFactorTargetID(*id)
	}
	return usu
}

// SetSecondFactorTarget sets the "second_factor_target" edge to the UserDevice entity.
func (usu *UserSettingsUpdate) SetSecondFactorTarget(u *UserDevice) *UserSettingsUpdate {
	return usu.SetSecondFactorTargetID(u.ID)
}

// AddNotificationTargetDeviceIDs adds the "notification_target_devices" edge to the UserDevice entity by IDs.
func (usu *UserSettingsUpdate) AddNotificationTargetDeviceIDs(ids ...int) *UserSettingsUpdate {
	usu.mutation.AddNotificationTargetDeviceIDs(ids...)
	return usu
}

// AddNotificationTargetDevices adds the "notification_target_devices" edges to the UserDevice entity.
func (usu *UserSettingsUpdate) AddNotificationTargetDevices(u ...*UserDevice) *UserSettingsUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return usu.AddNotificationTargetDeviceIDs(ids...)
}

// Mutation returns the UserSettingsMutation object of the builder.
func (usu *UserSettingsUpdate) Mutation() *UserSettingsMutation {
	return usu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (usu *UserSettingsUpdate) ClearOwner() *UserSettingsUpdate {
	usu.mutation.ClearOwner()
	return usu
}

// ClearSecondFactorTarget clears the "second_factor_target" edge to the UserDevice entity.
func (usu *UserSettingsUpdate) ClearSecondFactorTarget() *UserSettingsUpdate {
	usu.mutation.ClearSecondFactorTarget()
	return usu
}

// ClearNotificationTargetDevices clears all "notification_target_devices" edges to the UserDevice entity.
func (usu *UserSettingsUpdate) ClearNotificationTargetDevices() *UserSettingsUpdate {
	usu.mutation.ClearNotificationTargetDevices()
	return usu
}

// RemoveNotificationTargetDeviceIDs removes the "notification_target_devices" edge to UserDevice entities by IDs.
func (usu *UserSettingsUpdate) RemoveNotificationTargetDeviceIDs(ids ...int) *UserSettingsUpdate {
	usu.mutation.RemoveNotificationTargetDeviceIDs(ids...)
	return usu
}

// RemoveNotificationTargetDevices removes "notification_target_devices" edges to UserDevice entities.
func (usu *UserSettingsUpdate) RemoveNotificationTargetDevices(u ...*UserDevice) *UserSettingsUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return usu.RemoveNotificationTargetDeviceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (usu *UserSettingsUpdate) Save(ctx context.Context) (int, error) {
	usu.defaults()
	return withHooks(ctx, usu.sqlSave, usu.mutation, usu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (usu *UserSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := usu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (usu *UserSettingsUpdate) Exec(ctx context.Context) error {
	_, err := usu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usu *UserSettingsUpdate) ExecX(ctx context.Context) {
	if err := usu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (usu *UserSettingsUpdate) defaults() {
	if _, ok := usu.mutation.UpdatedAt(); !ok {
		v := usersettings.UpdateDefaultUpdatedAt()
		usu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (usu *UserSettingsUpdate) check() error {
	if v, ok := usu.mutation.UUID(); ok {
		if err := usersettings.UUIDValidator(v); err != nil {
			return &ValidationError{Name: "UUID", err: fmt.Errorf(`ent: validator failed for field "UserSettings.UUID": %w`, err)}
		}
	}
	if usu.mutation.OwnerCleared() && len(usu.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSettings.owner"`)
	}
	return nil
}

func (usu *UserSettingsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := usu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersettings.Table, usersettings.Columns, sqlgraph.NewFieldSpec(usersettings.FieldID, field.TypeInt))
	if ps := usu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usu.mutation.UUID(); ok {
		_spec.SetField(usersettings.FieldUUID, field.TypeString, value)
	}
	if value, ok := usu.mutation.TwoFactor(); ok {
		_spec.SetField(usersettings.FieldTwoFactor, field.TypeBool, value)
	}
	if value, ok := usu.mutation.NightMode(); ok {
		_spec.SetField(usersettings.FieldNightMode, field.TypeBool, value)
	}
	if value, ok := usu.mutation.CreatedAt(); ok {
		_spec.SetField(usersettings.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := usu.mutation.UpdatedAt(); ok {
		_spec.SetField(usersettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if usu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usersettings.OwnerTable,
			Columns: []string{usersettings.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usersettings.OwnerTable,
			Columns: []string{usersettings.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if usu.mutation.SecondFactorTargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   usersettings.SecondFactorTargetTable,
			Columns: []string{usersettings.SecondFactorTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usu.mutation.SecondFactorTargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   usersettings.SecondFactorTargetTable,
			Columns: []string{usersettings.SecondFactorTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if usu.mutation.NotificationTargetDevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersettings.NotificationTargetDevicesTable,
			Columns: []string{usersettings.NotificationTargetDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usu.mutation.RemovedNotificationTargetDevicesIDs(); len(nodes) > 0 && !usu.mutation.NotificationTargetDevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersettings.NotificationTargetDevicesTable,
			Columns: []string{usersettings.NotificationTargetDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usu.mutation.NotificationTargetDevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersettings.NotificationTargetDevicesTable,
			Columns: []string{usersettings.NotificationTargetDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, usu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	usu.mutation.done = true
	return n, nil
}

// UserSettingsUpdateOne is the builder for updating a single UserSettings entity.
type UserSettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserSettingsMutation
}

// SetUUID sets the "UUID" field.
func (usuo *UserSettingsUpdateOne) SetUUID(s string) *UserSettingsUpdateOne {
	usuo.mutation.SetUUID(s)
	return usuo
}

// SetNillableUUID sets the "UUID" field if the given value is not nil.
func (usuo *UserSettingsUpdateOne) SetNillableUUID(s *string) *UserSettingsUpdateOne {
	if s != nil {
		usuo.SetUUID(*s)
	}
	return usuo
}

// SetTwoFactor sets the "two_factor" field.
func (usuo *UserSettingsUpdateOne) SetTwoFactor(b bool) *UserSettingsUpdateOne {
	usuo.mutation.SetTwoFactor(b)
	return usuo
}

// SetNillableTwoFactor sets the "two_factor" field if the given value is not nil.
func (usuo *UserSettingsUpdateOne) SetNillableTwoFactor(b *bool) *UserSettingsUpdateOne {
	if b != nil {
		usuo.SetTwoFactor(*b)
	}
	return usuo
}

// SetNightMode sets the "night_mode" field.
func (usuo *UserSettingsUpdateOne) SetNightMode(b bool) *UserSettingsUpdateOne {
	usuo.mutation.SetNightMode(b)
	return usuo
}

// SetNillableNightMode sets the "night_mode" field if the given value is not nil.
func (usuo *UserSettingsUpdateOne) SetNillableNightMode(b *bool) *UserSettingsUpdateOne {
	if b != nil {
		usuo.SetNightMode(*b)
	}
	return usuo
}

// SetCreatedAt sets the "created_at" field.
func (usuo *UserSettingsUpdateOne) SetCreatedAt(t time.Time) *UserSettingsUpdateOne {
	usuo.mutation.SetCreatedAt(t)
	return usuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (usuo *UserSettingsUpdateOne) SetNillableCreatedAt(t *time.Time) *UserSettingsUpdateOne {
	if t != nil {
		usuo.SetCreatedAt(*t)
	}
	return usuo
}

// SetUpdatedAt sets the "updated_at" field.
func (usuo *UserSettingsUpdateOne) SetUpdatedAt(t time.Time) *UserSettingsUpdateOne {
	usuo.mutation.SetUpdatedAt(t)
	return usuo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (usuo *UserSettingsUpdateOne) SetOwnerID(id int) *UserSettingsUpdateOne {
	usuo.mutation.SetOwnerID(id)
	return usuo
}

// SetOwner sets the "owner" edge to the User entity.
func (usuo *UserSettingsUpdateOne) SetOwner(u *User) *UserSettingsUpdateOne {
	return usuo.SetOwnerID(u.ID)
}

// SetSecondFactorTargetID sets the "second_factor_target" edge to the UserDevice entity by ID.
func (usuo *UserSettingsUpdateOne) SetSecondFactorTargetID(id int) *UserSettingsUpdateOne {
	usuo.mutation.SetSecondFactorTargetID(id)
	return usuo
}

// SetNillableSecondFactorTargetID sets the "second_factor_target" edge to the UserDevice entity by ID if the given value is not nil.
func (usuo *UserSettingsUpdateOne) SetNillableSecondFactorTargetID(id *int) *UserSettingsUpdateOne {
	if id != nil {
		usuo = usuo.SetSecondFactorTargetID(*id)
	}
	return usuo
}

// SetSecondFactorTarget sets the "second_factor_target" edge to the UserDevice entity.
func (usuo *UserSettingsUpdateOne) SetSecondFactorTarget(u *UserDevice) *UserSettingsUpdateOne {
	return usuo.SetSecondFactorTargetID(u.ID)
}

// AddNotificationTargetDeviceIDs adds the "notification_target_devices" edge to the UserDevice entity by IDs.
func (usuo *UserSettingsUpdateOne) AddNotificationTargetDeviceIDs(ids ...int) *UserSettingsUpdateOne {
	usuo.mutation.AddNotificationTargetDeviceIDs(ids...)
	return usuo
}

// AddNotificationTargetDevices adds the "notification_target_devices" edges to the UserDevice entity.
func (usuo *UserSettingsUpdateOne) AddNotificationTargetDevices(u ...*UserDevice) *UserSettingsUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return usuo.AddNotificationTargetDeviceIDs(ids...)
}

// Mutation returns the UserSettingsMutation object of the builder.
func (usuo *UserSettingsUpdateOne) Mutation() *UserSettingsMutation {
	return usuo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (usuo *UserSettingsUpdateOne) ClearOwner() *UserSettingsUpdateOne {
	usuo.mutation.ClearOwner()
	return usuo
}

// ClearSecondFactorTarget clears the "second_factor_target" edge to the UserDevice entity.
func (usuo *UserSettingsUpdateOne) ClearSecondFactorTarget() *UserSettingsUpdateOne {
	usuo.mutation.ClearSecondFactorTarget()
	return usuo
}

// ClearNotificationTargetDevices clears all "notification_target_devices" edges to the UserDevice entity.
func (usuo *UserSettingsUpdateOne) ClearNotificationTargetDevices() *UserSettingsUpdateOne {
	usuo.mutation.ClearNotificationTargetDevices()
	return usuo
}

// RemoveNotificationTargetDeviceIDs removes the "notification_target_devices" edge to UserDevice entities by IDs.
func (usuo *UserSettingsUpdateOne) RemoveNotificationTargetDeviceIDs(ids ...int) *UserSettingsUpdateOne {
	usuo.mutation.RemoveNotificationTargetDeviceIDs(ids...)
	return usuo
}

// RemoveNotificationTargetDevices removes "notification_target_devices" edges to UserDevice entities.
func (usuo *UserSettingsUpdateOne) RemoveNotificationTargetDevices(u ...*UserDevice) *UserSettingsUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return usuo.RemoveNotificationTargetDeviceIDs(ids...)
}

// Where appends a list predicates to the UserSettingsUpdate builder.
func (usuo *UserSettingsUpdateOne) Where(ps ...predicate.UserSettings) *UserSettingsUpdateOne {
	usuo.mutation.Where(ps...)
	return usuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (usuo *UserSettingsUpdateOne) Select(field string, fields ...string) *UserSettingsUpdateOne {
	usuo.fields = append([]string{field}, fields...)
	return usuo
}

// Save executes the query and returns the updated UserSettings entity.
func (usuo *UserSettingsUpdateOne) Save(ctx context.Context) (*UserSettings, error) {
	usuo.defaults()
	return withHooks(ctx, usuo.sqlSave, usuo.mutation, usuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (usuo *UserSettingsUpdateOne) SaveX(ctx context.Context) *UserSettings {
	node, err := usuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (usuo *UserSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := usuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usuo *UserSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := usuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (usuo *UserSettingsUpdateOne) defaults() {
	if _, ok := usuo.mutation.UpdatedAt(); !ok {
		v := usersettings.UpdateDefaultUpdatedAt()
		usuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (usuo *UserSettingsUpdateOne) check() error {
	if v, ok := usuo.mutation.UUID(); ok {
		if err := usersettings.UUIDValidator(v); err != nil {
			return &ValidationError{Name: "UUID", err: fmt.Errorf(`ent: validator failed for field "UserSettings.UUID": %w`, err)}
		}
	}
	if usuo.mutation.OwnerCleared() && len(usuo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSettings.owner"`)
	}
	return nil
}

func (usuo *UserSettingsUpdateOne) sqlSave(ctx context.Context) (_node *UserSettings, err error) {
	if err := usuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersettings.Table, usersettings.Columns, sqlgraph.NewFieldSpec(usersettings.FieldID, field.TypeInt))
	id, ok := usuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := usuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersettings.FieldID)
		for _, f := range fields {
			if !usersettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := usuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usuo.mutation.UUID(); ok {
		_spec.SetField(usersettings.FieldUUID, field.TypeString, value)
	}
	if value, ok := usuo.mutation.TwoFactor(); ok {
		_spec.SetField(usersettings.FieldTwoFactor, field.TypeBool, value)
	}
	if value, ok := usuo.mutation.NightMode(); ok {
		_spec.SetField(usersettings.FieldNightMode, field.TypeBool, value)
	}
	if value, ok := usuo.mutation.CreatedAt(); ok {
		_spec.SetField(usersettings.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := usuo.mutation.UpdatedAt(); ok {
		_spec.SetField(usersettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if usuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usersettings.OwnerTable,
			Columns: []string{usersettings.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usersettings.OwnerTable,
			Columns: []string{usersettings.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if usuo.mutation.SecondFactorTargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   usersettings.SecondFactorTargetTable,
			Columns: []string{usersettings.SecondFactorTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usuo.mutation.SecondFactorTargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   usersettings.SecondFactorTargetTable,
			Columns: []string{usersettings.SecondFactorTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if usuo.mutation.NotificationTargetDevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersettings.NotificationTargetDevicesTable,
			Columns: []string{usersettings.NotificationTargetDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usuo.mutation.RemovedNotificationTargetDevicesIDs(); len(nodes) > 0 && !usuo.mutation.NotificationTargetDevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersettings.NotificationTargetDevicesTable,
			Columns: []string{usersettings.NotificationTargetDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := usuo.mutation.NotificationTargetDevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersettings.NotificationTargetDevicesTable,
			Columns: []string{usersettings.NotificationTargetDevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userdevice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserSettings{config: usuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, usuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	usuo.mutation.done = true
	return _node, nil
}
