// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"users-service/app/models/ent/entrepreneurdetails"
	"users-service/app/models/ent/location"
	"users-service/app/models/ent/predicate"
	"users-service/app/models/ent/user"
	"users-service/app/models/ent/userdetails"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserDetailsUpdate is the builder for updating UserDetails entities.
type UserDetailsUpdate struct {
	config
	hooks    []Hook
	mutation *UserDetailsMutation
}

// Where appends a list predicates to the UserDetailsUpdate builder.
func (udu *UserDetailsUpdate) Where(ps ...predicate.UserDetails) *UserDetailsUpdate {
	udu.mutation.Where(ps...)
	return udu
}

// SetName sets the "name" field.
func (udu *UserDetailsUpdate) SetName(s string) *UserDetailsUpdate {
	udu.mutation.SetName(s)
	return udu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (udu *UserDetailsUpdate) SetNillableName(s *string) *UserDetailsUpdate {
	if s != nil {
		udu.SetName(*s)
	}
	return udu
}

// SetFirstName sets the "first_name" field.
func (udu *UserDetailsUpdate) SetFirstName(s string) *UserDetailsUpdate {
	udu.mutation.SetFirstName(s)
	return udu
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (udu *UserDetailsUpdate) SetNillableFirstName(s *string) *UserDetailsUpdate {
	if s != nil {
		udu.SetFirstName(*s)
	}
	return udu
}

// ClearFirstName clears the value of the "first_name" field.
func (udu *UserDetailsUpdate) ClearFirstName() *UserDetailsUpdate {
	udu.mutation.ClearFirstName()
	return udu
}

// SetLastName sets the "last_name" field.
func (udu *UserDetailsUpdate) SetLastName(s string) *UserDetailsUpdate {
	udu.mutation.SetLastName(s)
	return udu
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (udu *UserDetailsUpdate) SetNillableLastName(s *string) *UserDetailsUpdate {
	if s != nil {
		udu.SetLastName(*s)
	}
	return udu
}

// ClearLastName clears the value of the "last_name" field.
func (udu *UserDetailsUpdate) ClearLastName() *UserDetailsUpdate {
	udu.mutation.ClearLastName()
	return udu
}

// SetUpdatedAt sets the "updated_at" field.
func (udu *UserDetailsUpdate) SetUpdatedAt(t time.Time) *UserDetailsUpdate {
	udu.mutation.SetUpdatedAt(t)
	return udu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (udu *UserDetailsUpdate) SetNillableUpdatedAt(t *time.Time) *UserDetailsUpdate {
	if t != nil {
		udu.SetUpdatedAt(*t)
	}
	return udu
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (udu *UserDetailsUpdate) SetOwnerID(id int) *UserDetailsUpdate {
	udu.mutation.SetOwnerID(id)
	return udu
}

// SetOwner sets the "owner" edge to the User entity.
func (udu *UserDetailsUpdate) SetOwner(u *User) *UserDetailsUpdate {
	return udu.SetOwnerID(u.ID)
}

// AddLocationIDs adds the "locations" edge to the Location entity by IDs.
func (udu *UserDetailsUpdate) AddLocationIDs(ids ...int) *UserDetailsUpdate {
	udu.mutation.AddLocationIDs(ids...)
	return udu
}

// AddLocations adds the "locations" edges to the Location entity.
func (udu *UserDetailsUpdate) AddLocations(l ...*Location) *UserDetailsUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return udu.AddLocationIDs(ids...)
}

// SetEntrepreneurDetailsID sets the "entrepreneur_details" edge to the EntrepreneurDetails entity by ID.
func (udu *UserDetailsUpdate) SetEntrepreneurDetailsID(id int) *UserDetailsUpdate {
	udu.mutation.SetEntrepreneurDetailsID(id)
	return udu
}

// SetNillableEntrepreneurDetailsID sets the "entrepreneur_details" edge to the EntrepreneurDetails entity by ID if the given value is not nil.
func (udu *UserDetailsUpdate) SetNillableEntrepreneurDetailsID(id *int) *UserDetailsUpdate {
	if id != nil {
		udu = udu.SetEntrepreneurDetailsID(*id)
	}
	return udu
}

// SetEntrepreneurDetails sets the "entrepreneur_details" edge to the EntrepreneurDetails entity.
func (udu *UserDetailsUpdate) SetEntrepreneurDetails(e *EntrepreneurDetails) *UserDetailsUpdate {
	return udu.SetEntrepreneurDetailsID(e.ID)
}

// Mutation returns the UserDetailsMutation object of the builder.
func (udu *UserDetailsUpdate) Mutation() *UserDetailsMutation {
	return udu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (udu *UserDetailsUpdate) ClearOwner() *UserDetailsUpdate {
	udu.mutation.ClearOwner()
	return udu
}

// ClearLocations clears all "locations" edges to the Location entity.
func (udu *UserDetailsUpdate) ClearLocations() *UserDetailsUpdate {
	udu.mutation.ClearLocations()
	return udu
}

// RemoveLocationIDs removes the "locations" edge to Location entities by IDs.
func (udu *UserDetailsUpdate) RemoveLocationIDs(ids ...int) *UserDetailsUpdate {
	udu.mutation.RemoveLocationIDs(ids...)
	return udu
}

// RemoveLocations removes "locations" edges to Location entities.
func (udu *UserDetailsUpdate) RemoveLocations(l ...*Location) *UserDetailsUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return udu.RemoveLocationIDs(ids...)
}

// ClearEntrepreneurDetails clears the "entrepreneur_details" edge to the EntrepreneurDetails entity.
func (udu *UserDetailsUpdate) ClearEntrepreneurDetails() *UserDetailsUpdate {
	udu.mutation.ClearEntrepreneurDetails()
	return udu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (udu *UserDetailsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, udu.sqlSave, udu.mutation, udu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (udu *UserDetailsUpdate) SaveX(ctx context.Context) int {
	affected, err := udu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (udu *UserDetailsUpdate) Exec(ctx context.Context) error {
	_, err := udu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (udu *UserDetailsUpdate) ExecX(ctx context.Context) {
	if err := udu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (udu *UserDetailsUpdate) check() error {
	if v, ok := udu.mutation.Name(); ok {
		if err := userdetails.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserDetails.name": %w`, err)}
		}
	}
	if udu.mutation.OwnerCleared() && len(udu.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserDetails.owner"`)
	}
	return nil
}

func (udu *UserDetailsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := udu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(userdetails.Table, userdetails.Columns, sqlgraph.NewFieldSpec(userdetails.FieldID, field.TypeInt))
	if ps := udu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := udu.mutation.Name(); ok {
		_spec.SetField(userdetails.FieldName, field.TypeString, value)
	}
	if value, ok := udu.mutation.FirstName(); ok {
		_spec.SetField(userdetails.FieldFirstName, field.TypeString, value)
	}
	if udu.mutation.FirstNameCleared() {
		_spec.ClearField(userdetails.FieldFirstName, field.TypeString)
	}
	if value, ok := udu.mutation.LastName(); ok {
		_spec.SetField(userdetails.FieldLastName, field.TypeString, value)
	}
	if udu.mutation.LastNameCleared() {
		_spec.ClearField(userdetails.FieldLastName, field.TypeString)
	}
	if value, ok := udu.mutation.UpdatedAt(); ok {
		_spec.SetField(userdetails.FieldUpdatedAt, field.TypeTime, value)
	}
	if udu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userdetails.OwnerTable,
			Columns: []string{userdetails.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := udu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userdetails.OwnerTable,
			Columns: []string{userdetails.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if udu.mutation.LocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userdetails.LocationsTable,
			Columns: []string{userdetails.LocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := udu.mutation.RemovedLocationsIDs(); len(nodes) > 0 && !udu.mutation.LocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userdetails.LocationsTable,
			Columns: []string{userdetails.LocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := udu.mutation.LocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userdetails.LocationsTable,
			Columns: []string{userdetails.LocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if udu.mutation.EntrepreneurDetailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   userdetails.EntrepreneurDetailsTable,
			Columns: []string{userdetails.EntrepreneurDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entrepreneurdetails.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := udu.mutation.EntrepreneurDetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   userdetails.EntrepreneurDetailsTable,
			Columns: []string{userdetails.EntrepreneurDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entrepreneurdetails.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, udu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdetails.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	udu.mutation.done = true
	return n, nil
}

// UserDetailsUpdateOne is the builder for updating a single UserDetails entity.
type UserDetailsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserDetailsMutation
}

// SetName sets the "name" field.
func (uduo *UserDetailsUpdateOne) SetName(s string) *UserDetailsUpdateOne {
	uduo.mutation.SetName(s)
	return uduo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uduo *UserDetailsUpdateOne) SetNillableName(s *string) *UserDetailsUpdateOne {
	if s != nil {
		uduo.SetName(*s)
	}
	return uduo
}

// SetFirstName sets the "first_name" field.
func (uduo *UserDetailsUpdateOne) SetFirstName(s string) *UserDetailsUpdateOne {
	uduo.mutation.SetFirstName(s)
	return uduo
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (uduo *UserDetailsUpdateOne) SetNillableFirstName(s *string) *UserDetailsUpdateOne {
	if s != nil {
		uduo.SetFirstName(*s)
	}
	return uduo
}

// ClearFirstName clears the value of the "first_name" field.
func (uduo *UserDetailsUpdateOne) ClearFirstName() *UserDetailsUpdateOne {
	uduo.mutation.ClearFirstName()
	return uduo
}

// SetLastName sets the "last_name" field.
func (uduo *UserDetailsUpdateOne) SetLastName(s string) *UserDetailsUpdateOne {
	uduo.mutation.SetLastName(s)
	return uduo
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (uduo *UserDetailsUpdateOne) SetNillableLastName(s *string) *UserDetailsUpdateOne {
	if s != nil {
		uduo.SetLastName(*s)
	}
	return uduo
}

// ClearLastName clears the value of the "last_name" field.
func (uduo *UserDetailsUpdateOne) ClearLastName() *UserDetailsUpdateOne {
	uduo.mutation.ClearLastName()
	return uduo
}

// SetUpdatedAt sets the "updated_at" field.
func (uduo *UserDetailsUpdateOne) SetUpdatedAt(t time.Time) *UserDetailsUpdateOne {
	uduo.mutation.SetUpdatedAt(t)
	return uduo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uduo *UserDetailsUpdateOne) SetNillableUpdatedAt(t *time.Time) *UserDetailsUpdateOne {
	if t != nil {
		uduo.SetUpdatedAt(*t)
	}
	return uduo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (uduo *UserDetailsUpdateOne) SetOwnerID(id int) *UserDetailsUpdateOne {
	uduo.mutation.SetOwnerID(id)
	return uduo
}

// SetOwner sets the "owner" edge to the User entity.
func (uduo *UserDetailsUpdateOne) SetOwner(u *User) *UserDetailsUpdateOne {
	return uduo.SetOwnerID(u.ID)
}

// AddLocationIDs adds the "locations" edge to the Location entity by IDs.
func (uduo *UserDetailsUpdateOne) AddLocationIDs(ids ...int) *UserDetailsUpdateOne {
	uduo.mutation.AddLocationIDs(ids...)
	return uduo
}

// AddLocations adds the "locations" edges to the Location entity.
func (uduo *UserDetailsUpdateOne) AddLocations(l ...*Location) *UserDetailsUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return uduo.AddLocationIDs(ids...)
}

// SetEntrepreneurDetailsID sets the "entrepreneur_details" edge to the EntrepreneurDetails entity by ID.
func (uduo *UserDetailsUpdateOne) SetEntrepreneurDetailsID(id int) *UserDetailsUpdateOne {
	uduo.mutation.SetEntrepreneurDetailsID(id)
	return uduo
}

// SetNillableEntrepreneurDetailsID sets the "entrepreneur_details" edge to the EntrepreneurDetails entity by ID if the given value is not nil.
func (uduo *UserDetailsUpdateOne) SetNillableEntrepreneurDetailsID(id *int) *UserDetailsUpdateOne {
	if id != nil {
		uduo = uduo.SetEntrepreneurDetailsID(*id)
	}
	return uduo
}

// SetEntrepreneurDetails sets the "entrepreneur_details" edge to the EntrepreneurDetails entity.
func (uduo *UserDetailsUpdateOne) SetEntrepreneurDetails(e *EntrepreneurDetails) *UserDetailsUpdateOne {
	return uduo.SetEntrepreneurDetailsID(e.ID)
}

// Mutation returns the UserDetailsMutation object of the builder.
func (uduo *UserDetailsUpdateOne) Mutation() *UserDetailsMutation {
	return uduo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (uduo *UserDetailsUpdateOne) ClearOwner() *UserDetailsUpdateOne {
	uduo.mutation.ClearOwner()
	return uduo
}

// ClearLocations clears all "locations" edges to the Location entity.
func (uduo *UserDetailsUpdateOne) ClearLocations() *UserDetailsUpdateOne {
	uduo.mutation.ClearLocations()
	return uduo
}

// RemoveLocationIDs removes the "locations" edge to Location entities by IDs.
func (uduo *UserDetailsUpdateOne) RemoveLocationIDs(ids ...int) *UserDetailsUpdateOne {
	uduo.mutation.RemoveLocationIDs(ids...)
	return uduo
}

// RemoveLocations removes "locations" edges to Location entities.
func (uduo *UserDetailsUpdateOne) RemoveLocations(l ...*Location) *UserDetailsUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return uduo.RemoveLocationIDs(ids...)
}

// ClearEntrepreneurDetails clears the "entrepreneur_details" edge to the EntrepreneurDetails entity.
func (uduo *UserDetailsUpdateOne) ClearEntrepreneurDetails() *UserDetailsUpdateOne {
	uduo.mutation.ClearEntrepreneurDetails()
	return uduo
}

// Where appends a list predicates to the UserDetailsUpdate builder.
func (uduo *UserDetailsUpdateOne) Where(ps ...predicate.UserDetails) *UserDetailsUpdateOne {
	uduo.mutation.Where(ps...)
	return uduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uduo *UserDetailsUpdateOne) Select(field string, fields ...string) *UserDetailsUpdateOne {
	uduo.fields = append([]string{field}, fields...)
	return uduo
}

// Save executes the query and returns the updated UserDetails entity.
func (uduo *UserDetailsUpdateOne) Save(ctx context.Context) (*UserDetails, error) {
	return withHooks(ctx, uduo.sqlSave, uduo.mutation, uduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uduo *UserDetailsUpdateOne) SaveX(ctx context.Context) *UserDetails {
	node, err := uduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uduo *UserDetailsUpdateOne) Exec(ctx context.Context) error {
	_, err := uduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uduo *UserDetailsUpdateOne) ExecX(ctx context.Context) {
	if err := uduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uduo *UserDetailsUpdateOne) check() error {
	if v, ok := uduo.mutation.Name(); ok {
		if err := userdetails.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserDetails.name": %w`, err)}
		}
	}
	if uduo.mutation.OwnerCleared() && len(uduo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserDetails.owner"`)
	}
	return nil
}

func (uduo *UserDetailsUpdateOne) sqlSave(ctx context.Context) (_node *UserDetails, err error) {
	if err := uduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userdetails.Table, userdetails.Columns, sqlgraph.NewFieldSpec(userdetails.FieldID, field.TypeInt))
	id, ok := uduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserDetails.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userdetails.FieldID)
		for _, f := range fields {
			if !userdetails.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userdetails.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uduo.mutation.Name(); ok {
		_spec.SetField(userdetails.FieldName, field.TypeString, value)
	}
	if value, ok := uduo.mutation.FirstName(); ok {
		_spec.SetField(userdetails.FieldFirstName, field.TypeString, value)
	}
	if uduo.mutation.FirstNameCleared() {
		_spec.ClearField(userdetails.FieldFirstName, field.TypeString)
	}
	if value, ok := uduo.mutation.LastName(); ok {
		_spec.SetField(userdetails.FieldLastName, field.TypeString, value)
	}
	if uduo.mutation.LastNameCleared() {
		_spec.ClearField(userdetails.FieldLastName, field.TypeString)
	}
	if value, ok := uduo.mutation.UpdatedAt(); ok {
		_spec.SetField(userdetails.FieldUpdatedAt, field.TypeTime, value)
	}
	if uduo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userdetails.OwnerTable,
			Columns: []string{userdetails.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uduo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userdetails.OwnerTable,
			Columns: []string{userdetails.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uduo.mutation.LocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userdetails.LocationsTable,
			Columns: []string{userdetails.LocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uduo.mutation.RemovedLocationsIDs(); len(nodes) > 0 && !uduo.mutation.LocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userdetails.LocationsTable,
			Columns: []string{userdetails.LocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uduo.mutation.LocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   userdetails.LocationsTable,
			Columns: []string{userdetails.LocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uduo.mutation.EntrepreneurDetailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   userdetails.EntrepreneurDetailsTable,
			Columns: []string{userdetails.EntrepreneurDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entrepreneurdetails.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uduo.mutation.EntrepreneurDetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   userdetails.EntrepreneurDetailsTable,
			Columns: []string{userdetails.EntrepreneurDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entrepreneurdetails.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserDetails{config: uduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdetails.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uduo.mutation.done = true
	return _node, nil
}
