// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"users-service/app/models/ent/user"
	"users-service/app/models/ent/userdevice"
	"users-service/app/models/ent/usersettings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserSettings is the model entity for the UserSettings schema.
type UserSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id"`
	// UUID holds the value of the "UUID" field.
	UUID string `json:"uuid"`
	// TwoFactor holds the value of the "two_factor" field.
	TwoFactor bool `json:"two_factor"`
	// NightMode holds the value of the "night_mode" field.
	NightMode bool `json:"night_mode"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserSettingsQuery when eager-loading is set.
	Edges              UserSettingsEdges `json:"edges"`
	user_user_settings *int
	selectValues       sql.SelectValues
}

// UserSettingsEdges holds the relations/edges for other nodes in the graph.
type UserSettingsEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner"`
	// SecondFactorTarget holds the value of the second_factor_target edge.
	SecondFactorTarget *UserDevice `json:"second_factor_target,omitempty"`
	// NotificationTargetDevices holds the value of the notification_target_devices edge.
	NotificationTargetDevices []*UserDevice `json:"notification_target_devices,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserSettingsEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// SecondFactorTargetOrErr returns the SecondFactorTarget value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserSettingsEdges) SecondFactorTargetOrErr() (*UserDevice, error) {
	if e.SecondFactorTarget != nil {
		return e.SecondFactorTarget, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: userdevice.Label}
	}
	return nil, &NotLoadedError{edge: "second_factor_target"}
}

// NotificationTargetDevicesOrErr returns the NotificationTargetDevices value or an error if the edge
// was not loaded in eager-loading.
func (e UserSettingsEdges) NotificationTargetDevicesOrErr() ([]*UserDevice, error) {
	if e.loadedTypes[2] {
		return e.NotificationTargetDevices, nil
	}
	return nil, &NotLoadedError{edge: "notification_target_devices"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usersettings.FieldTwoFactor, usersettings.FieldNightMode:
			values[i] = new(sql.NullBool)
		case usersettings.FieldID:
			values[i] = new(sql.NullInt64)
		case usersettings.FieldUUID:
			values[i] = new(sql.NullString)
		case usersettings.FieldCreatedAt, usersettings.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case usersettings.ForeignKeys[0]: // user_user_settings
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserSettings fields.
func (us *UserSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usersettings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			us.ID = int(value.Int64)
		case usersettings.FieldUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field UUID", values[i])
			} else if value.Valid {
				us.UUID = value.String
			}
		case usersettings.FieldTwoFactor:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field two_factor", values[i])
			} else if value.Valid {
				us.TwoFactor = value.Bool
			}
		case usersettings.FieldNightMode:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field night_mode", values[i])
			} else if value.Valid {
				us.NightMode = value.Bool
			}
		case usersettings.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				us.CreatedAt = value.Time
			}
		case usersettings.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				us.UpdatedAt = value.Time
			}
		case usersettings.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_user_settings", value)
			} else if value.Valid {
				us.user_user_settings = new(int)
				*us.user_user_settings = int(value.Int64)
			}
		default:
			us.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserSettings.
// This includes values selected through modifiers, order, etc.
func (us *UserSettings) Value(name string) (ent.Value, error) {
	return us.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the UserSettings entity.
func (us *UserSettings) QueryOwner() *UserQuery {
	return NewUserSettingsClient(us.config).QueryOwner(us)
}

// QuerySecondFactorTarget queries the "second_factor_target" edge of the UserSettings entity.
func (us *UserSettings) QuerySecondFactorTarget() *UserDeviceQuery {
	return NewUserSettingsClient(us.config).QuerySecondFactorTarget(us)
}

// QueryNotificationTargetDevices queries the "notification_target_devices" edge of the UserSettings entity.
func (us *UserSettings) QueryNotificationTargetDevices() *UserDeviceQuery {
	return NewUserSettingsClient(us.config).QueryNotificationTargetDevices(us)
}

// Update returns a builder for updating this UserSettings.
// Note that you need to call UserSettings.Unwrap() before calling this method if this UserSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (us *UserSettings) Update() *UserSettingsUpdateOne {
	return NewUserSettingsClient(us.config).UpdateOne(us)
}

// Unwrap unwraps the UserSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (us *UserSettings) Unwrap() *UserSettings {
	_tx, ok := us.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserSettings is not a transactional entity")
	}
	us.config.driver = _tx.drv
	return us
}

// String implements the fmt.Stringer.
func (us *UserSettings) String() string {
	var builder strings.Builder
	builder.WriteString("UserSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", us.ID))
	builder.WriteString("UUID=")
	builder.WriteString(us.UUID)
	builder.WriteString(", ")
	builder.WriteString("two_factor=")
	builder.WriteString(fmt.Sprintf("%v", us.TwoFactor))
	builder.WriteString(", ")
	builder.WriteString("night_mode=")
	builder.WriteString(fmt.Sprintf("%v", us.NightMode))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(us.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(us.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserSettingsSlice is a parsable slice of UserSettings.
type UserSettingsSlice []*UserSettings
