// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"users-service/app/models/ent/predicate"
	"users-service/app/models/ent/user"
	"users-service/app/models/ent/verificationcode"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VerificationCodeUpdate is the builder for updating VerificationCode entities.
type VerificationCodeUpdate struct {
	config
	hooks    []Hook
	mutation *VerificationCodeMutation
}

// Where appends a list predicates to the VerificationCodeUpdate builder.
func (vcu *VerificationCodeUpdate) Where(ps ...predicate.VerificationCode) *VerificationCodeUpdate {
	vcu.mutation.Where(ps...)
	return vcu
}

// SetCode sets the "code" field.
func (vcu *VerificationCodeUpdate) SetCode(s string) *VerificationCodeUpdate {
	vcu.mutation.SetCode(s)
	return vcu
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (vcu *VerificationCodeUpdate) SetNillableCode(s *string) *VerificationCodeUpdate {
	if s != nil {
		vcu.SetCode(*s)
	}
	return vcu
}

// SetCreatedAt sets the "created_at" field.
func (vcu *VerificationCodeUpdate) SetCreatedAt(t time.Time) *VerificationCodeUpdate {
	vcu.mutation.SetCreatedAt(t)
	return vcu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (vcu *VerificationCodeUpdate) SetNillableCreatedAt(t *time.Time) *VerificationCodeUpdate {
	if t != nil {
		vcu.SetCreatedAt(*t)
	}
	return vcu
}

// SetUpdatedAt sets the "updated_at" field.
func (vcu *VerificationCodeUpdate) SetUpdatedAt(t time.Time) *VerificationCodeUpdate {
	vcu.mutation.SetUpdatedAt(t)
	return vcu
}

// SetExpiresAt sets the "expires_at" field.
func (vcu *VerificationCodeUpdate) SetExpiresAt(t time.Time) *VerificationCodeUpdate {
	vcu.mutation.SetExpiresAt(t)
	return vcu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (vcu *VerificationCodeUpdate) SetNillableExpiresAt(t *time.Time) *VerificationCodeUpdate {
	if t != nil {
		vcu.SetExpiresAt(*t)
	}
	return vcu
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (vcu *VerificationCodeUpdate) SetOwnerID(id int) *VerificationCodeUpdate {
	vcu.mutation.SetOwnerID(id)
	return vcu
}

// SetOwner sets the "owner" edge to the User entity.
func (vcu *VerificationCodeUpdate) SetOwner(u *User) *VerificationCodeUpdate {
	return vcu.SetOwnerID(u.ID)
}

// Mutation returns the VerificationCodeMutation object of the builder.
func (vcu *VerificationCodeUpdate) Mutation() *VerificationCodeMutation {
	return vcu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (vcu *VerificationCodeUpdate) ClearOwner() *VerificationCodeUpdate {
	vcu.mutation.ClearOwner()
	return vcu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (vcu *VerificationCodeUpdate) Save(ctx context.Context) (int, error) {
	vcu.defaults()
	return withHooks(ctx, vcu.sqlSave, vcu.mutation, vcu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vcu *VerificationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := vcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vcu *VerificationCodeUpdate) Exec(ctx context.Context) error {
	_, err := vcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vcu *VerificationCodeUpdate) ExecX(ctx context.Context) {
	if err := vcu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vcu *VerificationCodeUpdate) defaults() {
	if _, ok := vcu.mutation.UpdatedAt(); !ok {
		v := verificationcode.UpdateDefaultUpdatedAt()
		vcu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vcu *VerificationCodeUpdate) check() error {
	if vcu.mutation.OwnerCleared() && len(vcu.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VerificationCode.owner"`)
	}
	return nil
}

func (vcu *VerificationCodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := vcu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(verificationcode.Table, verificationcode.Columns, sqlgraph.NewFieldSpec(verificationcode.FieldID, field.TypeInt))
	if ps := vcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vcu.mutation.Code(); ok {
		_spec.SetField(verificationcode.FieldCode, field.TypeString, value)
	}
	if value, ok := vcu.mutation.CreatedAt(); ok {
		_spec.SetField(verificationcode.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := vcu.mutation.UpdatedAt(); ok {
		_spec.SetField(verificationcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := vcu.mutation.ExpiresAt(); ok {
		_spec.SetField(verificationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if vcu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   verificationcode.OwnerTable,
			Columns: []string{verificationcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vcu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   verificationcode.OwnerTable,
			Columns: []string{verificationcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{verificationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	vcu.mutation.done = true
	return n, nil
}

// VerificationCodeUpdateOne is the builder for updating a single VerificationCode entity.
type VerificationCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VerificationCodeMutation
}

// SetCode sets the "code" field.
func (vcuo *VerificationCodeUpdateOne) SetCode(s string) *VerificationCodeUpdateOne {
	vcuo.mutation.SetCode(s)
	return vcuo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (vcuo *VerificationCodeUpdateOne) SetNillableCode(s *string) *VerificationCodeUpdateOne {
	if s != nil {
		vcuo.SetCode(*s)
	}
	return vcuo
}

// SetCreatedAt sets the "created_at" field.
func (vcuo *VerificationCodeUpdateOne) SetCreatedAt(t time.Time) *VerificationCodeUpdateOne {
	vcuo.mutation.SetCreatedAt(t)
	return vcuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (vcuo *VerificationCodeUpdateOne) SetNillableCreatedAt(t *time.Time) *VerificationCodeUpdateOne {
	if t != nil {
		vcuo.SetCreatedAt(*t)
	}
	return vcuo
}

// SetUpdatedAt sets the "updated_at" field.
func (vcuo *VerificationCodeUpdateOne) SetUpdatedAt(t time.Time) *VerificationCodeUpdateOne {
	vcuo.mutation.SetUpdatedAt(t)
	return vcuo
}

// SetExpiresAt sets the "expires_at" field.
func (vcuo *VerificationCodeUpdateOne) SetExpiresAt(t time.Time) *VerificationCodeUpdateOne {
	vcuo.mutation.SetExpiresAt(t)
	return vcuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (vcuo *VerificationCodeUpdateOne) SetNillableExpiresAt(t *time.Time) *VerificationCodeUpdateOne {
	if t != nil {
		vcuo.SetExpiresAt(*t)
	}
	return vcuo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (vcuo *VerificationCodeUpdateOne) SetOwnerID(id int) *VerificationCodeUpdateOne {
	vcuo.mutation.SetOwnerID(id)
	return vcuo
}

// SetOwner sets the "owner" edge to the User entity.
func (vcuo *VerificationCodeUpdateOne) SetOwner(u *User) *VerificationCodeUpdateOne {
	return vcuo.SetOwnerID(u.ID)
}

// Mutation returns the VerificationCodeMutation object of the builder.
func (vcuo *VerificationCodeUpdateOne) Mutation() *VerificationCodeMutation {
	return vcuo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (vcuo *VerificationCodeUpdateOne) ClearOwner() *VerificationCodeUpdateOne {
	vcuo.mutation.ClearOwner()
	return vcuo
}

// Where appends a list predicates to the VerificationCodeUpdate builder.
func (vcuo *VerificationCodeUpdateOne) Where(ps ...predicate.VerificationCode) *VerificationCodeUpdateOne {
	vcuo.mutation.Where(ps...)
	return vcuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (vcuo *VerificationCodeUpdateOne) Select(field string, fields ...string) *VerificationCodeUpdateOne {
	vcuo.fields = append([]string{field}, fields...)
	return vcuo
}

// Save executes the query and returns the updated VerificationCode entity.
func (vcuo *VerificationCodeUpdateOne) Save(ctx context.Context) (*VerificationCode, error) {
	vcuo.defaults()
	return withHooks(ctx, vcuo.sqlSave, vcuo.mutation, vcuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (vcuo *VerificationCodeUpdateOne) SaveX(ctx context.Context) *VerificationCode {
	node, err := vcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vcuo *VerificationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := vcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vcuo *VerificationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := vcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vcuo *VerificationCodeUpdateOne) defaults() {
	if _, ok := vcuo.mutation.UpdatedAt(); !ok {
		v := verificationcode.UpdateDefaultUpdatedAt()
		vcuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vcuo *VerificationCodeUpdateOne) check() error {
	if vcuo.mutation.OwnerCleared() && len(vcuo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VerificationCode.owner"`)
	}
	return nil
}

func (vcuo *VerificationCodeUpdateOne) sqlSave(ctx context.Context) (_node *VerificationCode, err error) {
	if err := vcuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(verificationcode.Table, verificationcode.Columns, sqlgraph.NewFieldSpec(verificationcode.FieldID, field.TypeInt))
	id, ok := vcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VerificationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := vcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, verificationcode.FieldID)
		for _, f := range fields {
			if !verificationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != verificationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := vcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vcuo.mutation.Code(); ok {
		_spec.SetField(verificationcode.FieldCode, field.TypeString, value)
	}
	if value, ok := vcuo.mutation.CreatedAt(); ok {
		_spec.SetField(verificationcode.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := vcuo.mutation.UpdatedAt(); ok {
		_spec.SetField(verificationcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := vcuo.mutation.ExpiresAt(); ok {
		_spec.SetField(verificationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if vcuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   verificationcode.OwnerTable,
			Columns: []string{verificationcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := vcuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   verificationcode.OwnerTable,
			Columns: []string{verificationcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VerificationCode{config: vcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, vcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{verificationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	vcuo.mutation.done = true
	return _node, nil
}
