// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"users-service/app/models/ent/user"
	"users-service/app/models/ent/verificationcode"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// VerificationCode is the model entity for the VerificationCode schema.
type VerificationCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id"`
	// Code holds the value of the "code" field.
	Code string `json:"code"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VerificationCodeQuery when eager-loading is set.
	Edges                  VerificationCodeEdges `json:"edges"`
	user_verification_code *int
	selectValues           sql.SelectValues
}

// VerificationCodeEdges holds the relations/edges for other nodes in the graph.
type VerificationCodeEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VerificationCodeEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VerificationCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case verificationcode.FieldID:
			values[i] = new(sql.NullInt64)
		case verificationcode.FieldCode:
			values[i] = new(sql.NullString)
		case verificationcode.FieldCreatedAt, verificationcode.FieldUpdatedAt, verificationcode.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case verificationcode.ForeignKeys[0]: // user_verification_code
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VerificationCode fields.
func (vc *VerificationCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case verificationcode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			vc.ID = int(value.Int64)
		case verificationcode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				vc.Code = value.String
			}
		case verificationcode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				vc.CreatedAt = value.Time
			}
		case verificationcode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				vc.UpdatedAt = value.Time
			}
		case verificationcode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				vc.ExpiresAt = value.Time
			}
		case verificationcode.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_verification_code", value)
			} else if value.Valid {
				vc.user_verification_code = new(int)
				*vc.user_verification_code = int(value.Int64)
			}
		default:
			vc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VerificationCode.
// This includes values selected through modifiers, order, etc.
func (vc *VerificationCode) Value(name string) (ent.Value, error) {
	return vc.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the VerificationCode entity.
func (vc *VerificationCode) QueryOwner() *UserQuery {
	return NewVerificationCodeClient(vc.config).QueryOwner(vc)
}

// Update returns a builder for updating this VerificationCode.
// Note that you need to call VerificationCode.Unwrap() before calling this method if this VerificationCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (vc *VerificationCode) Update() *VerificationCodeUpdateOne {
	return NewVerificationCodeClient(vc.config).UpdateOne(vc)
}

// Unwrap unwraps the VerificationCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (vc *VerificationCode) Unwrap() *VerificationCode {
	_tx, ok := vc.config.driver.(*txDriver)
	if !ok {
		panic("ent: VerificationCode is not a transactional entity")
	}
	vc.config.driver = _tx.drv
	return vc
}

// String implements the fmt.Stringer.
func (vc *VerificationCode) String() string {
	var builder strings.Builder
	builder.WriteString("VerificationCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", vc.ID))
	builder.WriteString("code=")
	builder.WriteString(vc.Code)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(vc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(vc.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(vc.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VerificationCodes is a parsable slice of VerificationCode.
type VerificationCodes []*VerificationCode
