name: Manage Python Dependencies

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package considered for update'
        required: true
        default: 'requests'
      version:
        description: 'new package version'
        required: true
        default: '1.0.0'

jobs:
  update-python-package:
    name: Update Python Package in requirements.txt
    uses: ./.github/workflows/reusable-update-requirements.yaml
    with:
      package_name: ${{ github.event.inputs.package }}
      package_version: ${{ github.event.inputs.version }}
      branch: 'development-branch'
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}