name: Reusable - Run Unit Tests

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.24'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go ${{ inputs.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Install Go test report tools
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest

      - name: Run Unit tests and generate reports
        run: |
          go test -v -tags=unit ./tests -args -test_type=unit -coverprofile=coverage.out | go-junit-report -set-exit-code > unit-tests.xml || true
          gocov-xml < coverage.out > coverage.xml

      - name: Upload Unit Test Results (JUnit XML)
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: unit-test-results
          path: unit-tests.xml
          retention-days: 7 

      - name: Upload Unit Test Coverage Report (Cobertura XML)
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: unit-coverage-report
          path: coverage.xml
          retention-days: 7
